# 05 - CatBoost Model Development

This notebook is the active modeling laboratory for CatBoost. The baseline notebook established a strong point-accuracy benchmark; the weather EDA notebook established what exogenous information is available. Here we treat CatBoost as a rolling adaptation problem: the experiment compares feature sets, target modes, retraining cadence, retuning cadence, training-window length, and recency weighting as one operational policy.

<p style="color:#b00020"><strong>Interpretation guide.</strong> A policy is the unit of comparison. Each policy says how often CatBoost retunes hyperparameters, how often it refits model weights inside the validation block, how much history it uses, and how much it upweights recent observations. The notebook rolls forward block by block, scores each policy on future origins, then lets the next block train and tune with the newly observed data included.</p>

> **Runtime note.** The default cells still run full Optuna tuning. The policy grid is deliberately compact rather than fully Cartesian: it compares a few interpretable adaptation regimes without exploding into every possible combination of cadence, window, and weighting.

## 1. Setup And Modeling Contract

The modeling problem is not just selecting a CatBoost feature matrix. Danish power prices drift, and the available tabular features only partially explain that drift. The central experiment is therefore a meta-optimization over learning policies: should the model keep all history, downweight old history, use a hard recent window, refit weekly, refit monthly, and retune every quarter?

For each validation block, CatBoost tunes candidates using only data available before the block, replays the chosen hyperparameters through the block on a retraining schedule, and scores every forecast origin. When the next block starts, the previous block's actuals are available for both training and tuning. This is the workflow a production learner would follow, minus the final publishing step.

In [1]:
from __future__ import annotations

import json
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from IPython.display import display

PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT != PROJECT_ROOT.parent and not (PROJECT_ROOT / "pyproject.toml").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

import sys
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from dkenergy_forecast.backtesting.horizons import make_daily_origins
from dkenergy_forecast.evaluation.summary import model_score_table
from dkenergy_forecast.io import load_price_panel
from dkenergy_forecast.features.price_features import (
    WEIGHTED_MEDIAN_BASELINE_COLUMN,
    add_weighted_median_baseline_feature,
    build_price_experiment_frame,
)
from dkenergy_forecast.tuning import (
    CatBoostValidationConfig,
    RecencyWeightSpec,
    build_candidate_grid,
    run_baseline_comparator,
    run_catboost_validation,
    write_catboost_validation_artifacts,
)
from dkenergy_forecast.tuning.catboost_validation import (
    make_retune_month_blocks,
    outer_month_score_table,
    outer_origins_for_months,
    prepare_nested_frame,
    validation_block_label,
)

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

In [2]:
PANEL_PATH = PROJECT_ROOT / "data" / "model_ready" / "price_panel_hourly_v1.parquet"
QA_PATH = PROJECT_ROOT / "data" / "model_ready" / "price_panel_hourly_v1.qa.json"
PRICE_FRAME_PATH = PROJECT_ROOT / "data" / "features" / "price_experiment_frame_policy_v1.parquet"
WEATHER_FRAME_PATH = PROJECT_ROOT / "data" / "features" / "weather_experiment_frame_backtest.parquet"
RESULT_ROOT = PROJECT_ROOT / "results" / "notebook_catboost_development_v1"
PRICE_RESULT_DIR = RESULT_ROOT / "price_policy_validation"
WEATHER_RESULT_DIR = RESULT_ROOT / "weather_policy_validation"

PRICE_FRAME_MONTHS = tuple(str(period) for period in pd.period_range("2012-01", "2026-06", freq="M"))
PRICE_BACKTEST_MONTHS = tuple(str(period) for period in pd.period_range("2013-04", "2026-06", freq="M"))
WEATHER_BACKTEST_MONTHS = tuple(str(period) for period in pd.period_range("2025-04", "2026-06", freq="M"))
RUN_FULL_TUNING = True
N_TRIALS = 8

BASE_TUNING_CONFIG = dict(
    n_trials=N_TRIALS,
    min_train_rows=1000,
    max_iterations=900,
    early_stopping_rounds=80,
    eval_origin_count=14,  # latest training origins reserved as CatBoost's fit-time eval_set
    random_seed=42,
    has_time=True,
    replay_all_candidates=True,
)

PRICE_POLICY_GRID = [
    dict(
        policy_label="q3_r7_full_hl180",
        retune_every_months=3,
        retrain_every_days=7,
        training_origin_days=None,
        recency=RecencyWeightSpec("exp_hl180", half_life_days=180),
        rationale="quarterly retune, weekly refit, all history with moderate recency bias",
    ),
    dict(
        policy_label="q3_r7_full_hl720",
        retune_every_months=3,
        retrain_every_days=7,
        training_origin_days=None,
        recency=RecencyWeightSpec("exp_hl720", half_life_days=720),
        rationale="quarterly retune, weekly refit, all history with weak recency bias",
    ),
    dict(
        policy_label="q3_r32_full_unweighted",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=None,
        recency=RecencyWeightSpec("unweighted"),
        rationale="quarterly retune, monthly-ish refit, all history as an anchor",
    ),
    dict(
        policy_label="q3_r32_full_hl180",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=None,
        recency=RecencyWeightSpec("exp_hl180", half_life_days=180),
        rationale="default middle path: all history plus moderate recency weighting",
    ),
    dict(
        policy_label="q3_r32_full_hl720",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=None,
        recency=RecencyWeightSpec("exp_hl720", half_life_days=720),
        rationale="conservative path: all history plus weak recency weighting",
    ),
    dict(
        policy_label="q3_r32_full_hl90_floor20",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=None,
        recency=RecencyWeightSpec("exp_hl90_floor20", half_life_days=90, floor=0.20),
        rationale="aggressive recency bias while keeping a 20% old-data anchor",
    ),
    dict(
        policy_label="q3_r32_365d_unweighted",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=365,
        recency=RecencyWeightSpec("unweighted"),
        rationale="hard one-year memory without extra recency weighting",
    ),
    dict(
        policy_label="q3_r32_365d_hl180",
        retune_every_months=3,
        retrain_every_days=32,
        training_origin_days=365,
        recency=RecencyWeightSpec("exp_hl180", half_life_days=180),
        rationale="one-year memory plus gentle weighting toward recent observations",
    ),
]

WEATHER_POLICY_GRID = [
    policy
    for policy in PRICE_POLICY_GRID
    if policy["policy_label"] not in {"q3_r7_full_hl720", "q3_r32_full_hl720"}
]

PRICE_FEATURE_SETS = [
    "price_full_engineered",
    "price_baseline_calendar",
    "price_lags_calendar",
]
WEATHER_FEATURE_SETS = [
    "price_full_engineered",
    "ensemble",
    "all_weather",
    "all_weather_plus_ensemble",
]
TARGET_MODES = ["direct", "residual_baseline"]
SEARCH_PROFILES = ["conservative"]

def policy_overview_rows(policies, *, experiment, backtest_months):
    return [
        {
            "experiment": experiment,
            "policy_label": policy["policy_label"],
            "retune_every_months": policy["retune_every_months"],
            "retrain_every_days": policy["retrain_every_days"],
            "training_origin_days": policy["training_origin_days"],
            "recency_label": policy["recency"].label,
            "sample_weight_half_life_days": policy["recency"].half_life_days,
            "sample_weight_floor": policy["recency"].floor,
            "validation_blocks": make_retune_month_blocks(
                backtest_months,
                retune_every_months=policy["retune_every_months"],
            ),
            "rationale": policy["rationale"],
        }
        for policy in policies
    ]


policy_overview = pd.DataFrame(
    policy_overview_rows(PRICE_POLICY_GRID, experiment="price", backtest_months=PRICE_BACKTEST_MONTHS)
    + policy_overview_rows(WEATHER_POLICY_GRID, experiment="weather", backtest_months=WEATHER_BACKTEST_MONTHS)
)
policy_overview

,experiment,policy_label,retune_every_months,retrain_every_days,training_origin_days,recency_label,sample_weight_half_life_days,sample_weight_floor,validation_blocks,rationale
0,price,q3_r7_full_hl180,3,7,NaN,exp_hl180,180.0,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...","quarterly retune, weekly refit, all history wi..."
1,price,q3_r7_full_hl720,3,7,NaN,exp_hl720,720.0,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...","quarterly retune, weekly refit, all history wi..."
2,price,q3_r32_full_unweighted,3,32,NaN,unweighted,NaN,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...","quarterly retune, monthly-ish refit, all histo..."
3,price,q3_r32_full_hl180,3,32,NaN,exp_hl180,180.0,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...",default middle path: all history plus moderate...
4,price,q3_r32_full_hl720,3,32,NaN,exp_hl720,720.0,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...",conservative path: all history plus weak recen...
5,price,q3_r32_full_hl90_floor20,3,32,NaN,exp_hl90_floor20,90.0,0.2,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...",aggressive recency bias while keeping a 20% ol...
6,price,q3_r32_365d_unweighted,3,32,365.0,unweighted,NaN,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...",hard one-year memory without extra recency wei...
7,price,q3_r32_365d_hl180,3,32,365.0,exp_hl180,180.0,NaN,"[(2013-04, 2013-05, 2013-06), (2013-07, 2013-0...",one-year memory plus gentle weighting toward r...
8,weather,q3_r7_full_hl180,3,7,NaN,exp_hl180,180.0,NaN,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...","quarterly retune, weekly refit, all history wi..."
9,weather,q3_r32_full_unweighted,3,32,NaN,unweighted,NaN,NaN,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...","quarterly retune, monthly-ish refit, all histo..."
10,weather,q3_r32_full_hl180,3,32,NaN,exp_hl180,180.0,NaN,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...",default middle path: all history plus moderate...
11,weather,q3_r32_full_hl90_floor20,3,32,NaN,exp_hl90_floor20,90.0,0.2,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...",aggressive recency bias while keeping a 20% ol...
12,weather,q3_r32_365d_unweighted,3,32,365.0,unweighted,NaN,NaN,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...",hard one-year memory without extra recency wei...
13,weather,q3_r32_365d_hl180,3,32,365.0,exp_hl180,180.0,NaN,"[(2025-04, 2025-05, 2025-06), (2025-07, 2025-0...",one-year memory plus gentle weighting toward r...

## 2. Load Price And Weather Experiment Frames

The price-only policy experiment can use the long EDS price history. The weather experiment cannot: the cached Open-Meteo feature frame starts in mid-2024. We therefore split the notebook into two arenas. `PRICE_FRAME_MONTHS` is the price-only context frame, while `PRICE_BACKTEST_MONTHS` is the scored price arena. The first scored month starts later than the frame so the first retune has prior training rows and a prior tuning-validation window. `PRICE_BACKTEST_MONTHS` starts in 2013-04 after the 2012 context year and a Jan-Mar tuning window. `WEATHER_BACKTEST_MONTHS` starts in 2025-04 for the same reason: the cached weather frame has enough mid-2024 context and a Jan-Mar tuning window before the first scored weather block.

In [3]:
def month_span_origins(panel, months, *, at_hour_utc=10):
    start = pd.Period(months[0], freq="M").to_timestamp().tz_localize("UTC")
    end = (pd.Period(months[-1], freq="M") + 1).to_timestamp().tz_localize("UTC")
    return make_daily_origins(panel, start=start, end=end, at_hour_utc=at_hour_utc)


def build_or_load_price_policy_frame(panel, months):
    if PRICE_FRAME_PATH.exists():
        cached = pd.read_parquet(PRICE_FRAME_PATH)
        cached = prepare_nested_frame(cached)
        missing = sorted(set(months) - set(cached["outer_month"].dropna().unique()))
        if not missing:
            return cached
        print(f"Cached price policy frame is missing month(s) {missing}; rebuilding {PRICE_FRAME_PATH}.")

    origins = month_span_origins(panel, months)
    output = build_price_experiment_frame(panel, origins)
    PRICE_FRAME_PATH.parent.mkdir(parents=True, exist_ok=True)
    output.to_parquet(PRICE_FRAME_PATH, index=False)
    return prepare_nested_frame(output)


def require_months(frame, months, label):
    missing = sorted(set(months) - set(frame["outer_month"].dropna().unique()))
    if missing:
        raise ValueError(f"{label} is missing requested backtest month(s): {missing}")


def require_complete_baseline(frame, label):
    if frame[WEIGHTED_MEDIAN_BASELINE_COLUMN].isna().any():
        missing = int(frame[WEIGHTED_MEDIAN_BASELINE_COLUMN].isna().sum())
        raise ValueError(
            f"{WEIGHTED_MEDIAN_BASELINE_COLUMN} must be complete for residual CatBoost in {label}; missing_rows={missing}"
        )


if not WEATHER_FRAME_PATH.exists():
    raise FileNotFoundError(
        f"Missing {WEATHER_FRAME_PATH}. Build it with scripts/build_weather_backtest_frame.py before running this notebook."
    )

panel = load_price_panel(PANEL_PATH, QA_PATH if QA_PATH.exists() else None)
price_frame = build_or_load_price_policy_frame(panel, PRICE_FRAME_MONTHS)
weather_frame = pd.read_parquet(WEATHER_FRAME_PATH)

if WEIGHTED_MEDIAN_BASELINE_COLUMN not in weather_frame.columns:
    print(
        f"Cached weather experiment frame is missing {WEIGHTED_MEDIAN_BASELINE_COLUMN}; "
        "adding it with the package price-feature builder and updating the cached parquet."
    )
    weather_frame = add_weighted_median_baseline_feature(weather_frame, panel)
    weather_frame.to_parquet(WEATHER_FRAME_PATH, index=False)

weather_frame = prepare_nested_frame(weather_frame)
require_months(price_frame, PRICE_FRAME_MONTHS, "price policy frame")
require_months(weather_frame, WEATHER_BACKTEST_MONTHS, "weather experiment frame")
require_complete_baseline(price_frame, "price policy frame")
require_complete_baseline(weather_frame, "weather experiment frame")

price_outer_origins = outer_origins_for_months(price_frame, PRICE_BACKTEST_MONTHS)
weather_outer_origins = outer_origins_for_months(weather_frame, WEATHER_BACKTEST_MONTHS)

price_coverage = (
    price_frame.groupby("outer_month")
    .agg(
        origins=("forecast_origin_utc", "nunique"),
        rows=("y", "size"),
        first_origin=("forecast_origin_utc", "min"),
        last_origin=("forecast_origin_utc", "max"),
    )
    .loc[list(PRICE_BACKTEST_MONTHS)]
    .assign(experiment="price")
)
weather_coverage = (
    weather_frame.groupby("outer_month")
    .agg(
        origins=("forecast_origin_utc", "nunique"),
        rows=("y", "size"),
        first_origin=("forecast_origin_utc", "min"),
        last_origin=("forecast_origin_utc", "max"),
    )
    .loc[list(WEATHER_BACKTEST_MONTHS)]
    .assign(experiment="weather")
)
coverage_table = pd.concat([price_coverage, weather_coverage]).reset_index().rename(columns={"index": "outer_month"})


def first_block_preflight(frame, *, experiment, backtest_months, policy_grid):
    rows = []
    frame = prepare_nested_frame(frame)
    first_scored_month = backtest_months[0]
    for policy in policy_grid:
        first_block_months = make_retune_month_blocks(
            backtest_months,
            retune_every_months=policy["retune_every_months"],
        )[0]
        retune_at = pd.Timestamp(f"{first_scored_month}-01T00:00:00Z")
        tuning_start = retune_at - pd.DateOffset(months=policy["retune_every_months"])
        tuning_end = retune_at
        train_mask = (
            (frame["forecast_origin_utc"] < tuning_start)
            & (frame["ds_utc"] < tuning_start)
            & frame["y"].notna()
        )
        if policy["training_origin_days"] is not None:
            train_mask &= frame["forecast_origin_utc"] >= tuning_start - pd.Timedelta(days=policy["training_origin_days"])
        train_origins = frame.loc[train_mask, "forecast_origin_utc"].drop_duplicates().sort_values()
        train_origin_span_days = (
            (train_origins.max() - train_origins.min()) / pd.Timedelta(days=1)
            if len(train_origins) > 1
            else 0
        )
        tuning_mask = (
            (frame["forecast_origin_utc"] >= tuning_start)
            & (frame["forecast_origin_utc"] < tuning_end)
        )
        scored_mask = frame["outer_month"].isin(first_block_months)
        rows.append({
            "experiment": experiment,
            "policy_label": policy["policy_label"],
            "first_scored_block": validation_block_label(first_block_months),
            "retune_at_utc": retune_at,
            "tuning_start_utc": tuning_start,
            "tuning_end_utc": tuning_end,
            "train_rows_before_tuning_window": int(train_mask.sum()),
            "train_origins_before_tuning_window": int(len(train_origins)),
            "train_origin_span_days": float(train_origin_span_days),
            "tuning_validation_origins": int(frame.loc[tuning_mask, "forecast_origin_utc"].nunique()),
            "scored_origins_in_first_block": int(frame.loc[scored_mask, "forecast_origin_utc"].nunique()),
            "passes_min_train_rows": bool(train_mask.sum() >= BASE_TUNING_CONFIG["min_train_rows"]),
        })
    return pd.DataFrame(rows)


preflight_table = pd.concat(
    [
        first_block_preflight(
            price_frame,
            experiment="price",
            backtest_months=PRICE_BACKTEST_MONTHS,
            policy_grid=PRICE_POLICY_GRID,
        ),
        first_block_preflight(
            weather_frame,
            experiment="weather",
            backtest_months=WEATHER_BACKTEST_MONTHS,
            policy_grid=WEATHER_POLICY_GRID,
        ),
    ],
    ignore_index=True,
)


def require_preflight_context(table):
    missing_context = table[
        ~table["passes_min_train_rows"]
        | table["tuning_validation_origins"].eq(0)
        | table["scored_origins_in_first_block"].eq(0)
    ]
    if not missing_context.empty:
        columns = [
            "experiment",
            "policy_label",
            "train_rows_before_tuning_window",
            "train_origins_before_tuning_window",
            "train_origin_span_days",
            "tuning_validation_origins",
            "scored_origins_in_first_block",
        ]
        raise ValueError(
            "First scored block lacks enough tuning/training context:\n"
            + missing_context[columns].to_string(index=False)
        )


require_preflight_context(preflight_table)
display(coverage_table)
preflight_table

    outer_month  origins  rows              first_origin               last_origin experiment
0       2013-04       30  1440 2013-04-01 10:00:00+00:00 2013-04-30 10:00:00+00:00      price
1       2013-05       31  1488 2013-05-01 10:00:00+00:00 2013-05-31 10:00:00+00:00      price
2       2013-06       30  1440 2013-06-01 10:00:00+00:00 2013-06-30 10:00:00+00:00      price
3       2013-07       31  1488 2013-07-01 10:00:00+00:00 2013-07-31 10:00:00+00:00      price
4       2013-08       31  1488 2013-08-01 10:00:00+00:00 2013-08-31 10:00:00+00:00      price
..          ...      ...   ...                       ...                       ...        ...
169     2026-02       28  1344 2026-02-01 10:00:00+00:00 2026-02-28 10:00:00+00:00    weather
170     2026-03       31  1486 2026-03-01 10:00:00+00:00 2026-03-31 10:00:00+00:00    weather
171     2026-04       30  1440 2026-04-01 10:00:00+00:00 2026-04-30 10:00:00+00:00    weather
172     2026-05       31  1488 2026-05-01 10:00:00+00:00 2026-05-31 10:00:00+00:00    weather
173     2026-06       29  1392 2026-06-01 10:00:00+00:00 2026-06-29 10:00:00+00:00    weather

[174 rows x 6 columns]

,experiment,policy_label,first_scored_block,retune_at_utc,tuning_start_utc,tuning_end_utc,train_rows_before_tuning_window,train_origins_before_tuning_window,train_origin_span_days,tuning_validation_origins,scored_origins_in_first_block,passes_min_train_rows
0,price,q3_r7_full_hl180,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
1,price,q3_r7_full_hl720,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
2,price,q3_r32_full_unweighted,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
3,price,q3_r32_full_hl180,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
4,price,q3_r32_full_hl720,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
5,price,q3_r32_full_hl90_floor20,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17522,366,365.0,90,91,True
6,price,q3_r32_365d_unweighted,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17474,365,364.0,90,91,True
7,price,q3_r32_365d_hl180,2013-04..2013-06,2013-04-01 00:00:00+00:00,2013-01-01 00:00:00+00:00,2013-04-01 00:00:00+00:00,17474,365,364.0,90,91,True
8,weather,q3_r7_full_hl180,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True
9,weather,q3_r32_full_unweighted,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True
10,weather,q3_r32_full_hl180,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True
11,weather,q3_r32_full_hl90_floor20,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True
12,weather,q3_r32_365d_unweighted,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True
13,weather,q3_r32_365d_hl180,2025-04..2025-06,2025-04-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-04-01 00:00:00+00:00,8836,185,184.0,90,91,True

<p style="color:#b00020"><strong>Interpretation.</strong> The long price arena tests adaptation policies across many market regimes. The weather arena answers a narrower question on the overlapping feature history: does weather add value once price-only policy behavior is understood? These two scores should not be collapsed as if they used the same historical span.</p>

## 3. Baselines On The Same Outer Origins

The production baselines are not a side note; they are the hurdle. A CatBoost model only matters if it beats these on the same outer origins, not on a convenient validation slice.

In [ ]:
price_baseline_predictions = run_baseline_comparator(
    panel,
    origins=price_outer_origins,
    min_train_days=365,
)
price_baseline_scores = model_score_table(price_baseline_predictions)
print(price_baseline_scores[price_baseline_scores["area"].eq("ALL")].sort_values("mae"))

weather_baseline_predictions = run_baseline_comparator(
    panel,
    origins=weather_outer_origins,
    min_train_days=365,
)
weather_baseline_scores = model_score_table(weather_baseline_predictions)
print(weather_baseline_scores[weather_baseline_scores["area"].eq("ALL")].sort_values("mae"))

                                         model_label area    rows  evaluated_rows         mae        rmse      bias  coverage  interval_width  missing_rate
0  median_weekday_exp_hl4_floor10_42d__median_wee...  ALL  232272          232272  151.269247  312.302673  4.405034       NaN             NaN           0.0
1                    rolling_median_hour_weekend_56d  ALL  232272          232272  169.965432  357.931495 -0.658050       NaN             NaN           0.0
2                                same_hour_last_week  ALL  232272          232272  189.401410  383.548085 -0.943815       NaN             NaN           0.0

## 4. Policy Grid Helpers

The policy grid is intentionally not a full Cartesian product. It compares a small set of interpretable regimes: fast versus monthly refitting, no recency bias versus moderate versus aggressive recency bias, and full-history versus hard one-year memory. Feature sets and target modes remain part of the candidate grid inside each policy.

In [6]:
from dkenergy_forecast.features import tabular_feature_columns_for_set


def policy_metadata(policy, *, family):
    recency = policy["recency"]
    return {
        "family": family,
        "policy_label": policy["policy_label"],
        "retune_every_months": policy["retune_every_months"],
        "retrain_every_days": policy["retrain_every_days"],
        "training_origin_days": policy["training_origin_days"],
        "policy_recency_label": recency.label,
        "policy_sample_weight_half_life_days": recency.half_life_days,
        "policy_sample_weight_floor": recency.floor,
        "policy_rationale": policy["rationale"],
    }


def policy_model_prefix(family, policy):
    return f"{family}_catboost__{policy['policy_label']}"


def policy_config(policy, *, family, backtest_months):
    return CatBoostValidationConfig(
        **BASE_TUNING_CONFIG,
        validation_months=backtest_months,
        retune_every_months=policy["retune_every_months"],
        retrain_every_days=policy["retrain_every_days"],
        training_origin_days=policy["training_origin_days"],
        model_prefix=policy_model_prefix(family, policy),
    )


def policy_candidates(feature_sets, policy):
    return build_candidate_grid(
        feature_sets=feature_sets,
        target_modes=TARGET_MODES,
        recency_specs=[policy["recency"]],
        search_profiles=SEARCH_PROFILES,
    )


def annotate_frame(frame, metadata):
    output = frame.copy()
    for key, value in metadata.items():
        output[key] = value
    return output


def annotate_result(result, policy, *, family):
    metadata = policy_metadata(policy, family=family)
    annotated_frames = {
        attribute: annotate_frame(getattr(result, attribute), metadata)
        for attribute in [
            "candidate_tuning_scores",
            "selected_validation_configs",
            "catboost_predictions",
            "catboost_replay_metadata",
            "feature_importance",
            "combined_model_scores",
            "outer_month_model_scores",
            "per_origin_model_scores",
            "per_origin_deltas",
        ]
    }
    return replace(result, **annotated_frames)


def run_policy_grid(*, family, feature_sets, output_dir, experiment_frame, baseline_predictions, backtest_months, policy_grid):
    if not RUN_FULL_TUNING:
        raise RuntimeError("RUN_FULL_TUNING is False. This notebook is configured to run full tuning by default.")

    results = {}
    for policy in policy_grid:
        policy_label = policy["policy_label"]
        candidates = policy_candidates(feature_sets, policy)
        config = policy_config(policy, family=family, backtest_months=backtest_months)
        print(f"=== {family} policy {policy_label}: {len(candidates)} candidate(s) ===")
        result = run_catboost_validation(
            experiment_frame,
            candidates=candidates,
            config=config,
            baseline_predictions=baseline_predictions,
            progress=print,
        )
        result = annotate_result(result, policy, family=family)
        write_catboost_validation_artifacts(
            output_dir / policy_label,
            result,
            manifest={
                "run_id": f"notebook_{family}_catboost_policy_{policy_label}",
                "created_at_utc": datetime.now(timezone.utc).isoformat(),
                "backtest_months": backtest_months,
                "feature_sets": feature_sets,
                "target_modes": TARGET_MODES,
                "search_profiles": SEARCH_PROFILES,
                "policy": policy_metadata(policy, family=family),
                "config": {
                    **BASE_TUNING_CONFIG,
                    "validation_months": backtest_months,
                    "retune_every_months": policy["retune_every_months"],
                    "retrain_every_days": policy["retrain_every_days"],
                    "training_origin_days": policy["training_origin_days"],
                },
            },
        )
        results[policy_label] = result
    return results


def concat_result_frames(results, attribute):
    frames = [getattr(result, attribute) for result in results.values()]
    frames = [frame for frame in frames if not frame.empty]
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


feature_counts = []
for experiment, experiment_frame, feature_sets in [
    ("price", price_frame, PRICE_FEATURE_SETS),
    ("weather", weather_frame, WEATHER_FEATURE_SETS),
]:
    for feature_set in feature_sets:
        columns = tabular_feature_columns_for_set(experiment_frame, feature_set)
        feature_counts.append({
            "experiment": experiment,
            "feature_set": feature_set,
            "feature_count": len(columns),
            "weather_feature_count": sum(column.startswith("weather_") for column in columns),
        })
pd.DataFrame(feature_counts).sort_values(["experiment", "weather_feature_count", "feature_set"])

  experiment                feature_set  feature_count  weather_feature_count
1      price    price_baseline_calendar              8                      0
0      price      price_full_engineered             21                      0
2      price        price_lags_calendar             12                      0
3    weather      price_full_engineered             21                      0
5    weather                all_weather             55                     34
4    weather                   ensemble             77                     56
6    weather  all_weather_plus_ensemble            111                     90

In [ ]:
price_results = run_policy_grid(
    family="price",
    feature_sets=PRICE_FEATURE_SETS,
    output_dir=PRICE_RESULT_DIR,
    experiment_frame=price_frame,
    baseline_predictions=price_baseline_predictions,
    backtest_months=PRICE_BACKTEST_MONTHS,
    policy_grid=PRICE_POLICY_GRID,
)

=== price policy q3_r7_full_hl180: 6 candidate(s) ===

/opt/homebrew/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:41,635] A new study created in memory with name: no-name-f6605f5b-9f75-4128-82a3-0a071c55a247

Retune 2013-04..2013-06: 91 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2013-01-01..2013-04-01 (21 features)...

[I 2026-07-05 16:51:41,868] Trial 0 finished with value: 50.021169715934874 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 50.021169715934874.
[I 2026-07-05 16:51:42,347] Trial 1 finished with value: 46.05859524932997 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 46.05859524932997.
[I 2026-07-05 16:51:42,675] Trial 2 finished with value: 51.2905501766498 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 46.05859524932997.
[I 2026-07-05 16:51:43,616] Trial 3 finished with value: 43.76302148288751 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 43.76302148288751.
[I 2026-07-05 16:51:43,813] Trial 4 finished with value: 49.2937022836611 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 43.76302148288751.
[I 2026-07-05 16:51:44,274] Trial 5 finished with value: 47.52346354747491 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 43.76302148288751.
[I 2026-07-05 16:51:44,416] Trial 6 finished with value: 48.93364560434964 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 43.76302148288751.
[I 2026-07-05 16:51:45,119] Trial 7 finished with value: 46.6163897520176 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 43.76302148288751.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:45,127] A new study created in memory with name: no-name-ff625bb3-386c-46e8-9073-bc55b215b669

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2013-01-01..2013-04-01 (21 features)...

[I 2026-07-05 16:51:45,919] Trial 0 finished with value: 44.731378567225946 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.731378567225946.
[I 2026-07-05 16:51:47,374] Trial 1 finished with value: 44.700643375126596 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 44.700643375126596.
[I 2026-07-05 16:51:47,714] Trial 2 finished with value: 43.31519569978263 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 43.31519569978263.
[I 2026-07-05 16:51:48,684] Trial 3 finished with value: 44.63182134440544 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 43.31519569978263.
[I 2026-07-05 16:51:48,978] Trial 4 finished with value: 44.749399787705315 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 43.31519569978263.
[I 2026-07-05 16:51:50,000] Trial 5 finished with value: 44.296815268053166 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 43.31519569978263.
[I 2026-07-05 16:51:50,282] Trial 6 finished with value: 44.656672058780345 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 43.31519569978263.
[I 2026-07-05 16:51:52,307] Trial 7 finished with value: 45.61193190635529 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 2 with value: 43.31519569978263.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:52,315] A new study created in memory with name: no-name-4c557296-a1ac-4aa6-90bd-a87dfc8e274e
[I 2026-07-05 16:51:52,446] Trial 0 finished with value: 57.66862854149407 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 57.66862854149407.

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2013-01-01..2013-04-01 (8 features)...

[I 2026-07-05 16:51:52,724] Trial 1 finished with value: 54.2432494316885 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:52,973] Trial 2 finished with value: 58.7455006544419 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:53,359] Trial 3 finished with value: 54.97641373314795 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:53,514] Trial 4 finished with value: 57.19934482393483 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:53,811] Trial 5 finished with value: 58.60040360237546 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:53,924] Trial 6 finished with value: 59.62209884141187 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 54.2432494316885.
[I 2026-07-05 16:51:54,285] Trial 7 finished with value: 56.6518439298078 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 1 with value: 54.2432494316885.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:54,293] A new study created in memory with name: no-name-91351b40-3b5d-46a2-906b-60e6b87b1c45
[I 2026-07-05 16:51:54,393] Trial 0 finished with value: 43.811957729620154 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 43.811957729620154.

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2013-01-01..2013-04-01 (8 features)...

[I 2026-07-05 16:51:54,582] Trial 1 finished with value: 43.798206171765685 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 43.798206171765685.
[I 2026-07-05 16:51:54,778] Trial 2 finished with value: 43.814570254074276 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 43.798206171765685.
[I 2026-07-05 16:51:55,109] Trial 3 finished with value: 43.81913297374968 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 43.798206171765685.
[I 2026-07-05 16:51:55,291] Trial 4 finished with value: 43.787410497124995 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 43.787410497124995.
[I 2026-07-05 16:51:55,553] Trial 5 finished with value: 43.86674941042649 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 43.787410497124995.
[I 2026-07-05 16:51:55,656] Trial 6 finished with value: 43.8345289394573 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 43.787410497124995.
[I 2026-07-05 16:51:55,935] Trial 7 finished with value: 43.783367859162695 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 43.783367859162695.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:55,942] A new study created in memory with name: no-name-be75b435-ca6c-44c3-998d-55046906b4e0
[I 2026-07-05 16:51:56,100] Trial 0 finished with value: 54.87930411687193 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 54.87930411687193.

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2013-01-01..2013-04-01 (12 features)...

[I 2026-07-05 16:51:56,799] Trial 1 finished with value: 44.952158488276204 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:57,114] Trial 2 finished with value: 54.59483072940359 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:57,547] Trial 3 finished with value: 51.20781991616262 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:57,760] Trial 4 finished with value: 45.908685245786536 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:58,436] Trial 5 finished with value: 45.36464041436999 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:58,600] Trial 6 finished with value: 53.510586030138825 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 44.952158488276204.
[I 2026-07-05 16:51:59,379] Trial 7 finished with value: 46.18767050949938 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 1 with value: 44.952158488276204.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:51:59,387] A new study created in memory with name: no-name-6916b589-0c60-4ff0-966d-59013b8f63a5
[I 2026-07-05 16:51:59,489] Trial 0 finished with value: 43.794437079083636 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 43.794437079083636.

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2013-01-01..2013-04-01 (12 features)...

[I 2026-07-05 16:51:59,739] Trial 1 finished with value: 43.59941062778481 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 43.59941062778481.
[I 2026-07-05 16:51:59,944] Trial 2 finished with value: 43.78665049164602 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 43.59941062778481.
[I 2026-07-05 16:52:00,366] Trial 3 finished with value: 43.15447118138933 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 43.15447118138933.
[I 2026-07-05 16:52:00,572] Trial 4 finished with value: 42.92492445143547 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 42.92492445143547.
[I 2026-07-05 16:52:00,959] Trial 5 finished with value: 43.062955280700095 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 42.92492445143547.
[I 2026-07-05 16:52:01,070] Trial 6 finished with value: 43.76748478808153 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 42.92492445143547.
[I 2026-07-05 16:52:01,398] Trial 7 finished with value: 43.666047905394656 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 42.92492445143547.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:10,200] A new study created in memory with name: no-name-c8ef9928-b406-4d4e-940d-bbaf5f60a563

Retune 2013-07..2013-09: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2013-04-01..2013-07-01 (21 features)...

[I 2026-07-05 16:53:10,838] Trial 0 finished with value: 51.93658881414564 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 51.93658881414564.
[I 2026-07-05 16:53:11,863] Trial 1 finished with value: 51.57022306306872 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 51.57022306306872.
[I 2026-07-05 16:53:12,847] Trial 2 finished with value: 51.954909324199214 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 51.57022306306872.
[I 2026-07-05 16:53:13,555] Trial 3 finished with value: 51.387882222068924 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 51.387882222068924.
[I 2026-07-05 16:53:13,826] Trial 4 finished with value: 53.09895734206149 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 51.387882222068924.
[I 2026-07-05 16:53:14,912] Trial 5 finished with value: 51.5318613960262 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 51.387882222068924.
[I 2026-07-05 16:53:15,231] Trial 6 finished with value: 52.24912926867329 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 51.387882222068924.
[I 2026-07-05 16:53:16,716] Trial 7 finished with value: 51.1649178216438 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 51.1649178216438.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:16,725] A new study created in memory with name: no-name-e5279fef-d95a-4dab-a993-8c2dd4988298

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2013-04-01..2013-07-01 (21 features)...

[I 2026-07-05 16:53:16,987] Trial 0 finished with value: 54.05110876277021 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 54.05110876277021.
[I 2026-07-05 16:53:17,429] Trial 1 finished with value: 54.49336130770484 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 54.05110876277021.
[I 2026-07-05 16:53:17,891] Trial 2 finished with value: 53.75953823017524 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 53.75953823017524.
[I 2026-07-05 16:53:18,474] Trial 3 finished with value: 53.08401216386682 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 53.08401216386682.
[I 2026-07-05 16:53:18,724] Trial 4 finished with value: 53.225758808064434 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 53.08401216386682.
[I 2026-07-05 16:53:19,418] Trial 5 finished with value: 52.29050769967504 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 52.29050769967504.
[I 2026-07-05 16:53:19,625] Trial 6 finished with value: 53.24250288576849 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 52.29050769967504.
[I 2026-07-05 16:53:20,467] Trial 7 finished with value: 53.055709871484055 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 52.29050769967504.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:20,476] A new study created in memory with name: no-name-ee3407d9-cbf2-4804-981a-0465040bf82b

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2013-04-01..2013-07-01 (8 features)...

[I 2026-07-05 16:53:21,191] Trial 0 finished with value: 56.30983280847251 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 56.30983280847251.
[I 2026-07-05 16:53:22,197] Trial 1 finished with value: 56.10970291151884 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 56.10970291151884.
[I 2026-07-05 16:53:23,230] Trial 2 finished with value: 56.50222471447263 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 56.10970291151884.
[I 2026-07-05 16:53:23,875] Trial 3 finished with value: 56.837748131518495 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 56.10970291151884.
[I 2026-07-05 16:53:24,165] Trial 4 finished with value: 55.80375821443668 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 55.80375821443668.
[I 2026-07-05 16:53:24,919] Trial 5 finished with value: 56.22673668009284 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 55.80375821443668.
[I 2026-07-05 16:53:25,266] Trial 6 finished with value: 56.75519483725366 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 55.80375821443668.
[I 2026-07-05 16:53:26,461] Trial 7 finished with value: 55.7291321317638 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 55.7291321317638.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:26,470] A new study created in memory with name: no-name-8dd98ff9-2fca-4964-80e4-4e0bf3857262
[I 2026-07-05 16:53:26,585] Trial 0 finished with value: 56.61856416340164 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 56.61856416340164.

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2013-04-01..2013-07-01 (8 features)...

[I 2026-07-05 16:53:26,792] Trial 1 finished with value: 56.581724267352996 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 56.581724267352996.
[I 2026-07-05 16:53:27,010] Trial 2 finished with value: 56.6044752339498 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 56.581724267352996.
[I 2026-07-05 16:53:27,361] Trial 3 finished with value: 56.563605120373545 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 56.563605120373545.
[I 2026-07-05 16:53:27,534] Trial 4 finished with value: 56.504032069606964 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 56.504032069606964.
[I 2026-07-05 16:53:27,812] Trial 5 finished with value: 56.609791023744705 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 56.504032069606964.
[I 2026-07-05 16:53:27,964] Trial 6 finished with value: 56.58239068400524 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 56.504032069606964.
[I 2026-07-05 16:53:28,261] Trial 7 finished with value: 56.61222362418645 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 56.504032069606964.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:28,270] A new study created in memory with name: no-name-d6ae80f1-a2db-482c-b9cb-5f39de4df780

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2013-04-01..2013-07-01 (12 features)...

[I 2026-07-05 16:53:29,024] Trial 0 finished with value: 52.901068751304095 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 52.901068751304095.
[I 2026-07-05 16:53:30,270] Trial 1 finished with value: 52.39110929217123 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 52.39110929217123.
[I 2026-07-05 16:53:31,673] Trial 2 finished with value: 53.03761269508292 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 52.39110929217123.
[I 2026-07-05 16:53:32,468] Trial 3 finished with value: 52.37515284438659 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 52.37515284438659.
[I 2026-07-05 16:53:32,808] Trial 4 finished with value: 52.89681045458062 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 52.37515284438659.
[I 2026-07-05 16:53:33,793] Trial 5 finished with value: 52.15971251370641 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 52.15971251370641.
[I 2026-07-05 16:53:34,198] Trial 6 finished with value: 52.851852586557406 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 52.15971251370641.
[I 2026-07-05 16:53:35,616] Trial 7 finished with value: 52.05748612051868 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 52.05748612051868.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:53:35,625] A new study created in memory with name: no-name-521afd31-a6b2-4af7-bfd2-7b5e64be1c9b

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2013-04-01..2013-07-01 (12 features)...

[I 2026-07-05 16:53:35,840] Trial 0 finished with value: 55.914250726828634 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 55.914250726828634.
[I 2026-07-05 16:53:36,350] Trial 1 finished with value: 55.38214170605901 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 55.38214170605901.
[I 2026-07-05 16:53:36,855] Trial 2 finished with value: 55.42849885173556 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 55.38214170605901.
[I 2026-07-05 16:53:37,331] Trial 3 finished with value: 55.64242927306817 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 55.38214170605901.
[I 2026-07-05 16:53:37,781] Trial 4 finished with value: 55.09119823427573 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 55.09119823427573.
[I 2026-07-05 16:53:38,284] Trial 5 finished with value: 55.507369458642394 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 55.09119823427573.
[I 2026-07-05 16:53:38,485] Trial 6 finished with value: 55.19716454267616 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 55.09119823427573.
[I 2026-07-05 16:53:39,304] Trial 7 finished with value: 54.93227002611237 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 54.93227002611237.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:56:26,944] A new study created in memory with name: no-name-e6efb622-4138-4af5-910b-1758b2c3cf4f

Retune 2013-10..2013-12: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2013-07-01..2013-10-01 (21 features)...

[I 2026-07-05 16:56:27,994] Trial 0 finished with value: 37.38469197294851 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.38469197294851.
[I 2026-07-05 16:56:29,740] Trial 1 finished with value: 36.833956561340166 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 36.833956561340166.
[I 2026-07-05 16:56:32,226] Trial 2 finished with value: 37.110169962723184 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 36.833956561340166.
[I 2026-07-05 16:56:33,975] Trial 3 finished with value: 36.638405853896366 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 36.638405853896366.
[I 2026-07-05 16:56:35,067] Trial 4 finished with value: 36.85708911752571 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 36.638405853896366.
[I 2026-07-05 16:56:36,402] Trial 5 finished with value: 37.011359425424466 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 36.638405853896366.
[I 2026-07-05 16:56:36,950] Trial 6 finished with value: 37.50137806846751 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 36.638405853896366.
[I 2026-07-05 16:56:41,825] Trial 7 finished with value: 36.232268986191244 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 36.232268986191244.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:56:41,836] A new study created in memory with name: no-name-1fd4aa7e-f156-403d-a504-112fd68a39f3

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2013-07-01..2013-10-01 (21 features)...

[I 2026-07-05 16:56:42,972] Trial 0 finished with value: 33.72091388604867 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:44,732] Trial 1 finished with value: 34.74027340615134 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:47,169] Trial 2 finished with value: 34.42122403096662 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:48,635] Trial 3 finished with value: 35.84723617280411 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:49,291] Trial 4 finished with value: 34.98933433095143 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:50,546] Trial 5 finished with value: 34.938685188361504 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:51,051] Trial 6 finished with value: 34.284024883257445 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 33.72091388604867.
[I 2026-07-05 16:56:55,649] Trial 7 finished with value: 36.71167955196301 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 33.72091388604867.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:56:55,659] A new study created in memory with name: no-name-77a644a2-e9e2-44bf-a4ea-5b15778453f6

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2013-07-01..2013-10-01 (8 features)...

[I 2026-07-05 16:56:56,600] Trial 0 finished with value: 41.08952909488496 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 41.08952909488496.
[I 2026-07-05 16:56:57,867] Trial 1 finished with value: 40.04614965751194 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 40.04614965751194.
[I 2026-07-05 16:56:59,554] Trial 2 finished with value: 40.6041321440508 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 40.04614965751194.
[I 2026-07-05 16:57:00,379] Trial 3 finished with value: 40.44949038295395 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 40.04614965751194.
[I 2026-07-05 16:57:00,788] Trial 4 finished with value: 39.280488934806506 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 39.280488934806506.
[I 2026-07-05 16:57:01,902] Trial 5 finished with value: 39.42529650662924 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 39.280488934806506.
[I 2026-07-05 16:57:02,354] Trial 6 finished with value: 40.685707914792395 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 39.280488934806506.
[I 2026-07-05 16:57:04,547] Trial 7 finished with value: 38.792263445086 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 38.792263445086.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:57:04,556] A new study created in memory with name: no-name-8625f105-ba63-406e-b08e-4131e7268050

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2013-07-01..2013-10-01 (8 features)...

[I 2026-07-05 16:57:05,175] Trial 0 finished with value: 36.27581374218403 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:06,203] Trial 1 finished with value: 36.62821165766184 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:07,601] Trial 2 finished with value: 36.34996521246872 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:08,446] Trial 3 finished with value: 36.802039386952316 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:08,882] Trial 4 finished with value: 37.14591351364927 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:09,932] Trial 5 finished with value: 36.8418069941191 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:10,392] Trial 6 finished with value: 36.66129986669196 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 36.27581374218403.
[I 2026-07-05 16:57:12,012] Trial 7 finished with value: 37.491649126262324 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 36.27581374218403.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:57:12,021] A new study created in memory with name: no-name-d351048c-11c9-4adb-b3cc-5ccebed84e48

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2013-07-01..2013-10-01 (12 features)...

[I 2026-07-05 16:57:13,071] Trial 0 finished with value: 39.28119018561003 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 39.28119018561003.
[I 2026-07-05 16:57:14,593] Trial 1 finished with value: 38.809623181399374 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 38.809623181399374.
[I 2026-07-05 16:57:16,892] Trial 2 finished with value: 38.179991039894205 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 38.179991039894205.
[I 2026-07-05 16:57:20,509] Trial 3 finished with value: 37.019359463040125 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 37.019359463040125.
[I 2026-07-05 16:57:21,502] Trial 4 finished with value: 38.16975506971589 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 37.019359463040125.
[I 2026-07-05 16:57:22,676] Trial 5 finished with value: 39.42725407922687 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 37.019359463040125.
[I 2026-07-05 16:57:23,205] Trial 6 finished with value: 38.77581341063046 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 37.019359463040125.
[I 2026-07-05 16:57:26,358] Trial 7 finished with value: 37.534948275677834 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 37.019359463040125.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:57:26,368] A new study created in memory with name: no-name-7129a054-f2a5-4e08-b227-d1b9e614eed3

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2013-07-01..2013-10-01 (12 features)...

[I 2026-07-05 16:57:27,368] Trial 0 finished with value: 34.39729818739859 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 34.39729818739859.
[I 2026-07-05 16:57:28,880] Trial 1 finished with value: 34.57598116141061 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 34.39729818739859.
[I 2026-07-05 16:57:30,813] Trial 2 finished with value: 34.45408835533188 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 34.39729818739859.
[I 2026-07-05 16:57:32,615] Trial 3 finished with value: 37.26422389232207 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 34.39729818739859.
[I 2026-07-05 16:57:33,884] Trial 4 finished with value: 38.509220993375415 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 34.39729818739859.
[I 2026-07-05 16:57:35,015] Trial 5 finished with value: 34.215828278363404 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 34.215828278363404.
[I 2026-07-05 16:57:35,482] Trial 6 finished with value: 34.68396612535929 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 34.215828278363404.
[I 2026-07-05 16:57:38,054] Trial 7 finished with value: 34.68970701666024 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 34.215828278363404.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 16:59:45,496] A new study created in memory with name: no-name-02f8a9fb-43f3-4765-a3a9-a79145b4d0bc

Retune 2014-01..2014-03: 90 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2013-10-01..2014-01-01 (21 features)...

[I 2026-07-05 16:59:46,744] Trial 0 finished with value: 51.553418225706594 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 51.553418225706594.
[I 2026-07-05 16:59:49,062] Trial 1 finished with value: 50.66117413678162 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 50.66117413678162.
[I 2026-07-05 16:59:51,741] Trial 2 finished with value: 51.133234873812796 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 50.66117413678162.
[I 2026-07-05 16:59:54,291] Trial 3 finished with value: 51.52315634210318 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 50.66117413678162.
[I 2026-07-05 16:59:55,320] Trial 4 finished with value: 51.47558959261723 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 50.66117413678162.
[I 2026-07-05 16:59:57,046] Trial 5 finished with value: 50.3679523109437 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 50.3679523109437.
[I 2026-07-05 16:59:57,642] Trial 6 finished with value: 51.14521788828448 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 50.3679523109437.
[I 2026-07-05 17:00:02,918] Trial 7 finished with value: 50.30239489243972 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 50.30239489243972.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:00:02,930] A new study created in memory with name: no-name-f9a78fe6-82a5-4693-b6f0-5872a5529618

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2013-10-01..2014-01-01 (21 features)...

[I 2026-07-05 17:00:03,424] Trial 0 finished with value: 54.05801379646016 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 54.05801379646016.
[I 2026-07-05 17:00:04,251] Trial 1 finished with value: 54.650711839398824 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 54.05801379646016.
[I 2026-07-05 17:00:05,185] Trial 2 finished with value: 54.3962385965178 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 54.05801379646016.
[I 2026-07-05 17:00:06,088] Trial 3 finished with value: 54.013561211491236 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 54.013561211491236.
[I 2026-07-05 17:00:06,445] Trial 4 finished with value: 54.98052949509874 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 54.013561211491236.
[I 2026-07-05 17:00:07,625] Trial 5 finished with value: 53.62752564867486 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 53.62752564867486.
[I 2026-07-05 17:00:07,998] Trial 6 finished with value: 54.65862955065293 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 53.62752564867486.
[I 2026-07-05 17:00:08,968] Trial 7 finished with value: 54.487988655971336 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 53.62752564867486.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:00:08,979] A new study created in memory with name: no-name-43778b6a-2e7a-4ae9-8027-a72eb7e04b6b

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2013-10-01..2014-01-01 (8 features)...

[I 2026-07-05 17:00:10,104] Trial 0 finished with value: 55.32258218605968 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 55.32258218605968.
[I 2026-07-05 17:00:11,877] Trial 1 finished with value: 55.281526050115616 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 55.281526050115616.
[I 2026-07-05 17:00:14,353] Trial 2 finished with value: 55.48242553686083 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 55.281526050115616.
[I 2026-07-05 17:00:17,316] Trial 3 finished with value: 55.880674428416825 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 55.281526050115616.
[I 2026-07-05 17:00:19,247] Trial 4 finished with value: 56.99152313379203 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 55.281526050115616.
[I 2026-07-05 17:00:20,734] Trial 5 finished with value: 54.92075784514064 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 54.92075784514064.
[I 2026-07-05 17:00:21,243] Trial 6 finished with value: 55.92338430138911 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 54.92075784514064.
[I 2026-07-05 17:00:25,643] Trial 7 finished with value: 55.162639015816474 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 54.92075784514064.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:00:25,654] A new study created in memory with name: no-name-395913e2-5094-4b61-9e63-3b6f44ffe7cf

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2013-10-01..2014-01-01 (8 features)...

[I 2026-07-05 17:00:26,140] Trial 0 finished with value: 55.85639753386692 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 55.85639753386692.
[I 2026-07-05 17:00:26,756] Trial 1 finished with value: 55.77009687878149 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 55.77009687878149.
[I 2026-07-05 17:00:27,853] Trial 2 finished with value: 55.56627980404614 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 55.56627980404614.
[I 2026-07-05 17:00:28,380] Trial 3 finished with value: 56.094291110782585 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 55.56627980404614.
[I 2026-07-05 17:00:28,703] Trial 4 finished with value: 55.48745135900113 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 55.48745135900113.
[I 2026-07-05 17:00:29,242] Trial 5 finished with value: 56.150881609343216 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 55.48745135900113.
[I 2026-07-05 17:00:29,610] Trial 6 finished with value: 55.84332189940283 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 55.48745135900113.
[I 2026-07-05 17:00:30,100] Trial 7 finished with value: 56.04968688426539 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 55.48745135900113.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:00:30,112] A new study created in memory with name: no-name-5d58a250-4c31-4ff9-9245-c477961675b8

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2013-10-01..2014-01-01 (12 features)...

[I 2026-07-05 17:00:31,266] Trial 0 finished with value: 52.738302262112384 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 52.738302262112384.
[I 2026-07-05 17:00:33,442] Trial 1 finished with value: 50.947040191128714 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:36,033] Trial 2 finished with value: 52.11518809780265 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:40,906] Trial 3 finished with value: 53.05253447830366 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:43,291] Trial 4 finished with value: 52.66098917910686 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:44,860] Trial 5 finished with value: 51.447830950876934 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:45,395] Trial 6 finished with value: 52.330335834725716 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 50.947040191128714.
[I 2026-07-05 17:00:50,387] Trial 7 finished with value: 51.33936287157901 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 1 with value: 50.947040191128714.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:00:50,399] A new study created in memory with name: no-name-114ca368-5b62-4aa1-807f-685c7a59ec0e

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2013-10-01..2014-01-01 (12 features)...

[I 2026-07-05 17:00:51,446] Trial 0 finished with value: 55.23075188710956 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 55.23075188710956.
[I 2026-07-05 17:00:52,965] Trial 1 finished with value: 54.816231482747135 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 54.816231482747135.
[I 2026-07-05 17:00:54,348] Trial 2 finished with value: 54.78508801817705 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 54.78508801817705.
[I 2026-07-05 17:00:55,245] Trial 3 finished with value: 54.71093621654395 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 54.71093621654395.
[I 2026-07-05 17:00:55,623] Trial 4 finished with value: 55.42007500744252 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 54.71093621654395.
[I 2026-07-05 17:00:56,981] Trial 5 finished with value: 55.011182449491685 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 54.71093621654395.
[I 2026-07-05 17:00:57,405] Trial 6 finished with value: 55.33535736936758 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 54.71093621654395.
[I 2026-07-05 17:00:58,747] Trial 7 finished with value: 54.70728877606566 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 54.70728877606566.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:03:28,566] A new study created in memory with name: no-name-486d343a-8b12-434f-aa7e-ec7396e6345d

Retune 2014-04..2014-06: 91 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2014-01-01..2014-04-01 (21 features)...

[I 2026-07-05 17:03:29,949] Trial 0 finished with value: 37.02131214672507 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.02131214672507.
[I 2026-07-05 17:03:32,437] Trial 1 finished with value: 37.082069113252636 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 37.02131214672507.
[I 2026-07-05 17:03:35,437] Trial 2 finished with value: 37.04689682176302 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 37.02131214672507.
[I 2026-07-05 17:03:37,615] Trial 3 finished with value: 40.47675419474522 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 37.02131214672507.
[I 2026-07-05 17:03:38,278] Trial 4 finished with value: 36.450539226077225 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 36.450539226077225.
[I 2026-07-05 17:03:40,162] Trial 5 finished with value: 36.633166016646435 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 36.450539226077225.
[I 2026-07-05 17:03:40,824] Trial 6 finished with value: 36.951296992180154 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 36.450539226077225.
[I 2026-07-05 17:03:44,746] Trial 7 finished with value: 36.743774643512815 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 36.450539226077225.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:03:44,757] A new study created in memory with name: no-name-2b46211c-c611-4a61-b9dc-1dce19cb1d57

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2014-01-01..2014-04-01 (21 features)...

[I 2026-07-05 17:03:46,132] Trial 0 finished with value: 37.24708113039318 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:48,645] Trial 1 finished with value: 37.423720076322205 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:51,693] Trial 2 finished with value: 37.38511680087647 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:54,359] Trial 3 finished with value: 37.929200885354916 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:55,130] Trial 4 finished with value: 38.325399974465476 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:57,100] Trial 5 finished with value: 37.482378796227835 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:03:57,760] Trial 6 finished with value: 37.58157113684321 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 37.24708113039318.
[I 2026-07-05 17:04:01,694] Trial 7 finished with value: 37.53956600370833 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 37.24708113039318.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:04:01,706] A new study created in memory with name: no-name-73dfebe1-f97e-4fa6-8ce8-2d9dea2c0316

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2014-01-01..2014-04-01 (8 features)...

[I 2026-07-05 17:04:02,943] Trial 0 finished with value: 46.92661039220766 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 46.92661039220766.
[I 2026-07-05 17:04:04,797] Trial 1 finished with value: 42.70424459755668 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 42.70424459755668.
[I 2026-07-05 17:04:06,732] Trial 2 finished with value: 46.04658546009349 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 42.70424459755668.
[I 2026-07-05 17:04:08,032] Trial 3 finished with value: 43.865941479253685 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 42.70424459755668.
[I 2026-07-05 17:04:08,830] Trial 4 finished with value: 42.45027040731859 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 42.45027040731859.
[I 2026-07-05 17:04:10,470] Trial 5 finished with value: 41.92972045692091 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 41.92972045692091.
[I 2026-07-05 17:04:10,968] Trial 6 finished with value: 47.654264201864464 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 41.92972045692091.
[I 2026-07-05 17:04:13,659] Trial 7 finished with value: 41.273122120972005 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 41.273122120972005.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:04:13,670] A new study created in memory with name: no-name-89ce14df-58bb-42c9-ae2c-dc6b141547b9

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2014-01-01..2014-04-01 (8 features)...

[I 2026-07-05 17:04:14,379] Trial 0 finished with value: 39.65670558659265 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 39.65670558659265.
[I 2026-07-05 17:04:15,457] Trial 1 finished with value: 39.49953604738016 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 39.49953604738016.
[I 2026-07-05 17:04:16,250] Trial 2 finished with value: 39.45521135485765 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 39.45521135485765.
[I 2026-07-05 17:04:17,144] Trial 3 finished with value: 39.743477136642085 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 39.45521135485765.
[I 2026-07-05 17:04:17,619] Trial 4 finished with value: 39.84658394367305 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 39.45521135485765.
[I 2026-07-05 17:04:18,276] Trial 5 finished with value: 39.04550135142259 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 39.04550135142259.
[I 2026-07-05 17:04:18,649] Trial 6 finished with value: 39.58396980111855 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 39.04550135142259.
[I 2026-07-05 17:04:19,445] Trial 7 finished with value: 39.11192425268159 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 39.04550135142259.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:04:19,457] A new study created in memory with name: no-name-8969645e-2936-41a1-b859-0b5272d02cf7

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2014-01-01..2014-04-01 (12 features)...

[I 2026-07-05 17:04:20,730] Trial 0 finished with value: 45.01677189999181 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 45.01677189999181.
[I 2026-07-05 17:04:22,843] Trial 1 finished with value: 43.63267906712908 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 43.63267906712908.
[I 2026-07-05 17:04:25,672] Trial 2 finished with value: 46.00393384361979 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 43.63267906712908.
[I 2026-07-05 17:04:27,475] Trial 3 finished with value: 44.30082805668632 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 43.63267906712908.
[I 2026-07-05 17:04:28,617] Trial 4 finished with value: 42.18622526751354 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 42.18622526751354.
[I 2026-07-05 17:04:30,308] Trial 5 finished with value: 43.34316213586676 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 42.18622526751354.
[I 2026-07-05 17:04:30,906] Trial 6 finished with value: 47.16243952579495 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 42.18622526751354.
[I 2026-07-05 17:04:36,406] Trial 7 finished with value: 41.88342123661093 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 41.88342123661093.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:04:36,418] A new study created in memory with name: no-name-b73d93e8-6a0e-40fe-81db-6e37b067dc16

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2014-01-01..2014-04-01 (12 features)...

[I 2026-07-05 17:04:37,730] Trial 0 finished with value: 37.834865395694145 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:39,845] Trial 1 finished with value: 38.024448817006245 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:42,707] Trial 2 finished with value: 37.839779208853955 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:44,538] Trial 3 finished with value: 38.1113863228319 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:45,779] Trial 4 finished with value: 37.924708752049426 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:47,434] Trial 5 finished with value: 38.058570481267 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:48,072] Trial 6 finished with value: 37.947595313292304 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 37.834865395694145.
[I 2026-07-05 17:04:53,669] Trial 7 finished with value: 38.39329618243786 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 37.834865395694145.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:17,211] A new study created in memory with name: no-name-0a6c8836-3202-4818-9fb5-1816d88c89aa

Retune 2014-07..2014-09: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2014-04-01..2014-07-01 (21 features)...

[I 2026-07-05 17:07:18,023] Trial 0 finished with value: 36.3521218168628 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.3521218168628.
[I 2026-07-05 17:07:19,478] Trial 1 finished with value: 35.88117402190306 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 35.88117402190306.
[I 2026-07-05 17:07:20,751] Trial 2 finished with value: 36.021532320232275 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 35.88117402190306.
[I 2026-07-05 17:07:21,838] Trial 3 finished with value: 35.82211429652444 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 35.82211429652444.
[I 2026-07-05 17:07:22,515] Trial 4 finished with value: 34.970732252982195 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 34.970732252982195.
[I 2026-07-05 17:07:24,324] Trial 5 finished with value: 35.44194027115096 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 34.970732252982195.
[I 2026-07-05 17:07:24,767] Trial 6 finished with value: 36.072495451856476 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 34.970732252982195.
[I 2026-07-05 17:07:26,735] Trial 7 finished with value: 35.68225661573079 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 34.970732252982195.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:26,748] A new study created in memory with name: no-name-7b98fe1e-1f5d-43f4-a480-c5f8813a3070

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2014-04-01..2014-07-01 (21 features)...

[I 2026-07-05 17:07:26,958] Trial 0 finished with value: 36.995214250257554 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.995214250257554.
[I 2026-07-05 17:07:27,453] Trial 1 finished with value: 36.92285033400807 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 36.92285033400807.
[I 2026-07-05 17:07:27,817] Trial 2 finished with value: 36.96905580526144 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 36.92285033400807.
[I 2026-07-05 17:07:28,592] Trial 3 finished with value: 36.946581948040965 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 36.92285033400807.
[I 2026-07-05 17:07:28,986] Trial 4 finished with value: 36.463586716285796 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 36.463586716285796.
[I 2026-07-05 17:07:29,683] Trial 5 finished with value: 36.63143842459654 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 36.463586716285796.
[I 2026-07-05 17:07:29,906] Trial 6 finished with value: 36.92019249203569 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 36.463586716285796.
[I 2026-07-05 17:07:30,971] Trial 7 finished with value: 36.17749999694544 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 36.17749999694544.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:30,984] A new study created in memory with name: no-name-6172d18e-3733-4773-b8ea-14971e7160f6

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2014-04-01..2014-07-01 (8 features)...

[I 2026-07-05 17:07:32,323] Trial 0 finished with value: 35.61770893711178 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 35.61770893711178.
[I 2026-07-05 17:07:34,177] Trial 1 finished with value: 36.03359426599722 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 35.61770893711178.
[I 2026-07-05 17:07:36,281] Trial 2 finished with value: 35.60309324701337 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 35.60309324701337.
[I 2026-07-05 17:07:37,470] Trial 3 finished with value: 35.81713276473155 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 35.60309324701337.
[I 2026-07-05 17:07:38,256] Trial 4 finished with value: 36.12057178315075 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 35.60309324701337.
[I 2026-07-05 17:07:39,967] Trial 5 finished with value: 35.989741475072755 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 35.60309324701337.
[I 2026-07-05 17:07:40,636] Trial 6 finished with value: 35.60406486365565 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 35.60309324701337.
[I 2026-07-05 17:07:42,474] Trial 7 finished with value: 36.07599906623713 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 2 with value: 35.60309324701337.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:42,487] A new study created in memory with name: no-name-932996dd-2b4f-4378-803f-2991d52de144

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2014-04-01..2014-07-01 (8 features)...

[I 2026-07-05 17:07:42,774] Trial 0 finished with value: 36.70460392506842 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:43,136] Trial 1 finished with value: 36.98312431190851 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:43,514] Trial 2 finished with value: 36.99260709294107 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:44,122] Trial 3 finished with value: 36.95444728587422 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:44,425] Trial 4 finished with value: 36.959882373790215 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:44,905] Trial 5 finished with value: 36.978420679280305 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:45,126] Trial 6 finished with value: 36.83618453075369 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 36.70460392506842.
[I 2026-07-05 17:07:45,639] Trial 7 finished with value: 36.98575411300998 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 36.70460392506842.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:45,652] A new study created in memory with name: no-name-9b8ab2e0-01d9-4cc9-9baf-74ab094e87b2

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2014-04-01..2014-07-01 (12 features)...

[I 2026-07-05 17:07:47,098] Trial 0 finished with value: 36.318492403900294 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.318492403900294.
[I 2026-07-05 17:07:49,373] Trial 1 finished with value: 35.60328974987584 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 35.60328974987584.
[I 2026-07-05 17:07:52,459] Trial 2 finished with value: 35.538568724616276 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 35.538568724616276.
[I 2026-07-05 17:07:53,712] Trial 3 finished with value: 35.662002978127155 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 35.538568724616276.
[I 2026-07-05 17:07:54,569] Trial 4 finished with value: 36.092968702309314 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 35.538568724616276.
[I 2026-07-05 17:07:56,420] Trial 5 finished with value: 35.99811271253227 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 35.538568724616276.
[I 2026-07-05 17:07:57,220] Trial 6 finished with value: 36.062913270009105 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 35.538568724616276.
[I 2026-07-05 17:07:59,830] Trial 7 finished with value: 35.56507551221125 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 2 with value: 35.538568724616276.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:07:59,842] A new study created in memory with name: no-name-2723b2ed-cce4-415e-9df6-ff373fcb1e67

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2014-04-01..2014-07-01 (12 features)...

[I 2026-07-05 17:08:00,082] Trial 0 finished with value: 36.98088474974356 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.98088474974356.
[I 2026-07-05 17:08:00,486] Trial 1 finished with value: 36.98054345167909 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 36.98054345167909.
[I 2026-07-05 17:08:00,840] Trial 2 finished with value: 36.986272635869184 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 36.98054345167909.
[I 2026-07-05 17:08:01,497] Trial 3 finished with value: 36.95449992071005 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 36.95449992071005.
[I 2026-07-05 17:08:01,807] Trial 4 finished with value: 37.01273407204262 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 36.95449992071005.
[I 2026-07-05 17:08:02,312] Trial 5 finished with value: 36.97934213580899 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 36.95449992071005.
[I 2026-07-05 17:08:02,523] Trial 6 finished with value: 36.939638122238065 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 36.939638122238065.
[I 2026-07-05 17:08:03,064] Trial 7 finished with value: 36.97251095582636 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 36.939638122238065.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:10:50,318] A new study created in memory with name: no-name-93743783-f422-419c-926b-02407580dd70

Retune 2014-10..2014-12: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2014-07-01..2014-10-01 (21 features)...

[I 2026-07-05 17:10:51,904] Trial 0 finished with value: 24.266060357771373 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 24.266060357771373.
[I 2026-07-05 17:10:54,646] Trial 1 finished with value: 24.07968154857611 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 24.07968154857611.
[I 2026-07-05 17:10:57,693] Trial 2 finished with value: 24.154411565757396 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 24.07968154857611.
[I 2026-07-05 17:10:59,969] Trial 3 finished with value: 23.951487940738936 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 23.951487940738936.
[I 2026-07-05 17:11:00,746] Trial 4 finished with value: 24.646979889761724 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 23.951487940738936.
[I 2026-07-05 17:11:02,786] Trial 5 finished with value: 24.142325242397632 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 23.951487940738936.
[I 2026-07-05 17:11:03,630] Trial 6 finished with value: 24.258103690389703 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 23.951487940738936.
[I 2026-07-05 17:11:07,863] Trial 7 finished with value: 23.651407147758036 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 23.651407147758036.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:11:07,876] A new study created in memory with name: no-name-7fd5d76f-f8b4-4581-942a-370ef6b12944

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2014-07-01..2014-10-01 (21 features)...

[I 2026-07-05 17:11:09,464] Trial 0 finished with value: 24.071946891469583 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 24.071946891469583.
[I 2026-07-05 17:11:12,080] Trial 1 finished with value: 24.412518664036064 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 24.071946891469583.
[I 2026-07-05 17:11:15,754] Trial 2 finished with value: 23.979018643632994 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 23.979018643632994.
[I 2026-07-05 17:11:18,143] Trial 3 finished with value: 23.54003681618952 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 23.54003681618952.
[I 2026-07-05 17:11:19,398] Trial 4 finished with value: 24.429356884732464 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 23.54003681618952.
[I 2026-07-05 17:11:21,540] Trial 5 finished with value: 24.547540049846965 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 23.54003681618952.
[I 2026-07-05 17:11:22,421] Trial 6 finished with value: 24.16073269126988 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 23.54003681618952.
[I 2026-07-05 17:11:27,490] Trial 7 finished with value: 24.172755586593798 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 23.54003681618952.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:11:27,504] A new study created in memory with name: no-name-86feec05-9f6a-4979-89de-ca4e412eb66a

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2014-07-01..2014-10-01 (8 features)...

[I 2026-07-05 17:11:28,949] Trial 0 finished with value: 25.463254357845287 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 25.463254357845287.
[I 2026-07-05 17:11:29,879] Trial 1 finished with value: 25.601906073730667 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 25.463254357845287.
[I 2026-07-05 17:11:33,035] Trial 2 finished with value: 25.153897634890978 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 25.153897634890978.
[I 2026-07-05 17:11:35,452] Trial 3 finished with value: 24.533874049070356 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 24.533874049070356.
[I 2026-07-05 17:11:37,249] Trial 4 finished with value: 24.68762256972838 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 24.533874049070356.
[I 2026-07-05 17:11:38,970] Trial 5 finished with value: 25.055656740761176 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 24.533874049070356.
[I 2026-07-05 17:11:39,657] Trial 6 finished with value: 25.220668265362768 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 24.533874049070356.
[I 2026-07-05 17:11:43,167] Trial 7 finished with value: 25.0012864778729 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 24.533874049070356.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:11:43,180] A new study created in memory with name: no-name-7e267f15-9dbf-4c91-a771-06aef80c8451

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2014-07-01..2014-10-01 (8 features)...

[I 2026-07-05 17:11:44,609] Trial 0 finished with value: 24.69731225004119 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 24.69731225004119.
[I 2026-07-05 17:11:46,587] Trial 1 finished with value: 24.489754840521336 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 24.489754840521336.
[I 2026-07-05 17:11:49,844] Trial 2 finished with value: 24.536425565534664 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 24.489754840521336.
[I 2026-07-05 17:11:51,379] Trial 3 finished with value: 24.36971381135877 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 24.36971381135877.
[I 2026-07-05 17:11:52,442] Trial 4 finished with value: 24.585346523282855 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 24.36971381135877.
[I 2026-07-05 17:11:54,124] Trial 5 finished with value: 24.686157625856417 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 24.36971381135877.
[I 2026-07-05 17:11:54,812] Trial 6 finished with value: 24.710547350141457 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 24.36971381135877.
[I 2026-07-05 17:11:58,125] Trial 7 finished with value: 24.556667434277596 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 24.36971381135877.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:11:58,137] A new study created in memory with name: no-name-124ec1bd-71c4-4ce5-af90-51094b0b0d71

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2014-07-01..2014-10-01 (12 features)...

[I 2026-07-05 17:11:59,622] Trial 0 finished with value: 25.58065946947663 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 25.58065946947663.
[I 2026-07-05 17:12:01,947] Trial 1 finished with value: 24.640532510501682 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:05,222] Trial 2 finished with value: 25.216883600777052 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:07,208] Trial 3 finished with value: 24.69361215298976 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:09,604] Trial 4 finished with value: 25.070821909437687 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:11,446] Trial 5 finished with value: 25.0886710619415 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:12,160] Trial 6 finished with value: 25.477096163897542 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 24.640532510501682.
[I 2026-07-05 17:12:18,077] Trial 7 finished with value: 23.96430384337384 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 23.96430384337384.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:12:18,090] A new study created in memory with name: no-name-1c944772-177e-41b7-972c-a040438b600f

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2014-07-01..2014-10-01 (12 features)...

[I 2026-07-05 17:12:19,561] Trial 0 finished with value: 24.9901916890287 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 24.9901916890287.
[I 2026-07-05 17:12:21,771] Trial 1 finished with value: 25.101948708740156 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 24.9901916890287.
[I 2026-07-05 17:12:25,042] Trial 2 finished with value: 24.750945139860796 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 24.750945139860796.
[I 2026-07-05 17:12:28,320] Trial 3 finished with value: 24.955760380954885 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 24.750945139860796.
[I 2026-07-05 17:12:31,123] Trial 4 finished with value: 24.989126303219255 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 24.750945139860796.
[I 2026-07-05 17:12:32,952] Trial 5 finished with value: 25.56797963330831 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 24.750945139860796.
[I 2026-07-05 17:12:33,673] Trial 6 finished with value: 24.780354553457006 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 24.750945139860796.
[I 2026-07-05 17:12:39,429] Trial 7 finished with value: 25.1189918173883 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 2 with value: 24.750945139860796.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:15:58,954] A new study created in memory with name: no-name-7e4b1700-c1e4-42b1-b96e-9f8cdca3d7d6

Retune 2015-01..2015-03: 90 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2014-10-01..2015-01-01 (21 features)...

[I 2026-07-05 17:16:00,705] Trial 0 finished with value: 43.10634498703487 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 43.10634498703487.
[I 2026-07-05 17:16:03,468] Trial 1 finished with value: 42.60657522979197 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 42.60657522979197.
[I 2026-07-05 17:16:07,184] Trial 2 finished with value: 43.112725965114315 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 42.60657522979197.
[I 2026-07-05 17:16:12,447] Trial 3 finished with value: 43.2988228616119 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 42.60657522979197.
[I 2026-07-05 17:16:14,760] Trial 4 finished with value: 43.04428489754551 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 42.60657522979197.
[I 2026-07-05 17:16:16,911] Trial 5 finished with value: 42.475944243017025 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 42.475944243017025.
[I 2026-07-05 17:16:17,752] Trial 6 finished with value: 42.89708585539747 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 42.475944243017025.
[I 2026-07-05 17:16:23,825] Trial 7 finished with value: 42.46883653295401 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 42.46883653295401.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:16:23,838] A new study created in memory with name: no-name-f5ea8fa7-3ebb-4388-8626-108125c2ea3e

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2014-10-01..2015-01-01 (21 features)...

[I 2026-07-05 17:16:24,079] Trial 0 finished with value: 48.18721528111232 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 48.18721528111232.
[I 2026-07-05 17:16:24,563] Trial 1 finished with value: 48.15798731238893 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 48.15798731238893.
[I 2026-07-05 17:16:25,032] Trial 2 finished with value: 48.11235705879227 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 48.11235705879227.
[I 2026-07-05 17:16:27,788] Trial 3 finished with value: 44.566979374589565 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 44.566979374589565.
[I 2026-07-05 17:16:28,177] Trial 4 finished with value: 47.590176939187806 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 44.566979374589565.
[I 2026-07-05 17:16:28,798] Trial 5 finished with value: 48.14330276311345 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 44.566979374589565.
[I 2026-07-05 17:16:29,067] Trial 6 finished with value: 47.943792401666535 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 44.566979374589565.
[I 2026-07-05 17:16:29,837] Trial 7 finished with value: 47.872829026172255 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 44.566979374589565.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:16:29,850] A new study created in memory with name: no-name-20f75e9f-a892-4ad9-a749-c54efcd8b717

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2014-10-01..2015-01-01 (8 features)...

[I 2026-07-05 17:16:31,405] Trial 0 finished with value: 48.69467475042621 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 48.69467475042621.
[I 2026-07-05 17:16:33,570] Trial 1 finished with value: 47.48847628849565 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 47.48847628849565.
[I 2026-07-05 17:16:37,117] Trial 2 finished with value: 49.57003978189364 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 47.48847628849565.
[I 2026-07-05 17:16:39,680] Trial 3 finished with value: 47.98253797757949 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 47.48847628849565.
[I 2026-07-05 17:16:41,260] Trial 4 finished with value: 47.49919990472763 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 47.48847628849565.
[I 2026-07-05 17:16:43,108] Trial 5 finished with value: 47.160882275798926 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 47.160882275798926.
[I 2026-07-05 17:16:43,866] Trial 6 finished with value: 49.24349208974115 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 47.160882275798926.
[I 2026-07-05 17:16:48,769] Trial 7 finished with value: 47.95578116924381 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 5 with value: 47.160882275798926.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:16:48,783] A new study created in memory with name: no-name-33c827a0-0b37-4d22-ba50-3b7db7545b72

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2014-10-01..2015-01-01 (8 features)...

[I 2026-07-05 17:16:50,360] Trial 0 finished with value: 49.01359106702925 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 49.01359106702925.
[I 2026-07-05 17:16:52,554] Trial 1 finished with value: 47.69193829007248 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:16:53,576] Trial 2 finished with value: 48.623568184626066 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:16:55,289] Trial 3 finished with value: 48.303945054756305 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:16:56,351] Trial 4 finished with value: 47.74343528153214 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:16:58,178] Trial 5 finished with value: 48.04369065472708 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:16:58,791] Trial 6 finished with value: 49.133814809895426 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 47.69193829007248.
[I 2026-07-05 17:17:04,151] Trial 7 finished with value: 49.19119547709442 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 1 with value: 47.69193829007248.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:17:04,165] A new study created in memory with name: no-name-c477990d-ec57-43d4-a1bd-36f3b10f8e92

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2014-10-01..2015-01-01 (12 features)...

[I 2026-07-05 17:17:05,813] Trial 0 finished with value: 44.40731613350676 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.40731613350676.
[I 2026-07-05 17:17:08,299] Trial 1 finished with value: 43.41595805157143 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 43.41595805157143.
[I 2026-07-05 17:17:10,577] Trial 2 finished with value: 44.427983844352376 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 43.41595805157143.
[I 2026-07-05 17:17:12,659] Trial 3 finished with value: 43.356789334619094 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 43.356789334619094.
[I 2026-07-05 17:17:15,031] Trial 4 finished with value: 42.94524205341228 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 42.94524205341228.
[I 2026-07-05 17:17:17,150] Trial 5 finished with value: 43.79309747850201 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 42.94524205341228.
[I 2026-07-05 17:17:18,032] Trial 6 finished with value: 43.96287271421408 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 42.94524205341228.
[I 2026-07-05 17:17:22,419] Trial 7 finished with value: 42.86343685349652 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 42.86343685349652.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:17:22,432] A new study created in memory with name: no-name-232b7ebe-09fa-4bf2-9a56-ac7bab924d95

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2014-10-01..2015-01-01 (12 features)...

[I 2026-07-05 17:17:24,078] Trial 0 finished with value: 48.51291352449674 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 48.51291352449674.
[I 2026-07-05 17:17:26,474] Trial 1 finished with value: 47.933077753451606 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 47.933077753451606.
[I 2026-07-05 17:17:30,053] Trial 2 finished with value: 48.702546888776894 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 47.933077753451606.
[I 2026-07-05 17:17:31,309] Trial 3 finished with value: 47.797703860326905 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 47.797703860326905.
[I 2026-07-05 17:17:32,259] Trial 4 finished with value: 48.56901594302159 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 47.797703860326905.
[I 2026-07-05 17:17:33,910] Trial 5 finished with value: 47.53031532855401 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 47.53031532855401.
[I 2026-07-05 17:17:34,689] Trial 6 finished with value: 48.866281850064084 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 47.53031532855401.
[I 2026-07-05 17:17:36,586] Trial 7 finished with value: 47.49486163410097 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 47.49486163410097.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:22:08,741] A new study created in memory with name: no-name-51b5ac27-d5c1-476c-861a-393256175801

Retune 2015-04..2015-06: 91 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2015-01-01..2015-04-01 (21 features)...

[I 2026-07-05 17:22:09,320] Trial 0 finished with value: 41.16563036111024 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 41.16563036111024.
[I 2026-07-05 17:22:10,955] Trial 1 finished with value: 39.83196634645132 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 39.83196634645132.
[I 2026-07-05 17:22:11,953] Trial 2 finished with value: 41.13090893302341 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 39.83196634645132.
[I 2026-07-05 17:22:13,249] Trial 3 finished with value: 43.360758133603326 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 39.83196634645132.
[I 2026-07-05 17:22:13,867] Trial 4 finished with value: 40.01199386922051 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 39.83196634645132.
[I 2026-07-05 17:22:16,101] Trial 5 finished with value: 38.16567266501193 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 38.16567266501193.
[I 2026-07-05 17:22:16,549] Trial 6 finished with value: 38.087737077350425 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 38.087737077350425.
[I 2026-07-05 17:22:18,928] Trial 7 finished with value: 41.421581987515 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 38.087737077350425.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:22:18,943] A new study created in memory with name: no-name-7af1fdba-7785-4a55-bc54-693b0ebb87f7

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2015-01-01..2015-04-01 (21 features)...

[I 2026-07-05 17:22:20,042] Trial 0 finished with value: 36.50631661870408 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.50631661870408.
[I 2026-07-05 17:22:21,424] Trial 1 finished with value: 36.826996257688556 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 36.50631661870408.
[I 2026-07-05 17:22:22,531] Trial 2 finished with value: 36.86690357177737 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 36.50631661870408.
[I 2026-07-05 17:22:25,212] Trial 3 finished with value: 35.9745448626159 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 35.9745448626159.
[I 2026-07-05 17:22:25,785] Trial 4 finished with value: 36.636366752517134 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 35.9745448626159.
[I 2026-07-05 17:22:28,613] Trial 5 finished with value: 36.1059934078649 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 35.9745448626159.
[I 2026-07-05 17:22:29,128] Trial 6 finished with value: 36.814607911351786 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 35.9745448626159.
[I 2026-07-05 17:22:32,702] Trial 7 finished with value: 36.38301289227304 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 35.9745448626159.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:22:32,717] A new study created in memory with name: no-name-34dd8371-d641-4167-9a5b-d6aada9b7dbc

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2015-01-01..2015-04-01 (8 features)...

[I 2026-07-05 17:22:34,389] Trial 0 finished with value: 38.412498001225785 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:36,388] Trial 1 finished with value: 40.00935709116349 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:37,931] Trial 2 finished with value: 40.026737150513384 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:39,324] Trial 3 finished with value: 40.352336668949846 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:40,443] Trial 4 finished with value: 39.413893759355695 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:42,000] Trial 5 finished with value: 42.19589657509665 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 38.412498001225785.
[I 2026-07-05 17:22:42,800] Trial 6 finished with value: 37.665173483397744 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 37.665173483397744.
[I 2026-07-05 17:22:45,514] Trial 7 finished with value: 39.33417881320267 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 37.665173483397744.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:22:45,528] A new study created in memory with name: no-name-6580d9ff-2146-4f5c-905c-1d7d3817dd2e

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2015-01-01..2015-04-01 (8 features)...

[I 2026-07-05 17:22:46,105] Trial 0 finished with value: 38.05759113659636 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 38.05759113659636.
[I 2026-07-05 17:22:47,104] Trial 1 finished with value: 38.30983665398477 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 38.05759113659636.
[I 2026-07-05 17:22:47,795] Trial 2 finished with value: 38.05444456797657 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 38.05444456797657.
[I 2026-07-05 17:22:49,522] Trial 3 finished with value: 38.05464367568079 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 38.05444456797657.
[I 2026-07-05 17:22:50,557] Trial 4 finished with value: 38.51234453729806 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 38.05444456797657.
[I 2026-07-05 17:22:52,957] Trial 5 finished with value: 38.09902917291087 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 38.05444456797657.
[I 2026-07-05 17:22:53,365] Trial 6 finished with value: 37.6151483427476 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 37.6151483427476.
[I 2026-07-05 17:22:55,040] Trial 7 finished with value: 38.13495825459224 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 37.6151483427476.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:22:55,054] A new study created in memory with name: no-name-09e15ee8-b5e3-4ab8-a98f-1a83992f8d0b

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2015-01-01..2015-04-01 (12 features)...

[I 2026-07-05 17:22:55,724] Trial 0 finished with value: 44.76173272426464 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:22:56,910] Trial 1 finished with value: 45.75469798712464 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:22:57,839] Trial 2 finished with value: 45.43386765257797 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:22:58,954] Trial 3 finished with value: 45.321120708107586 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:22:59,476] Trial 4 finished with value: 47.04455934801557 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:23:00,727] Trial 5 finished with value: 46.50826014202086 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:23:01,086] Trial 6 finished with value: 46.2555226886859 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 44.76173272426464.
[I 2026-07-05 17:23:02,693] Trial 7 finished with value: 45.97313754661923 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 44.76173272426464.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:23:02,707] A new study created in memory with name: no-name-80cccba3-495c-4005-88ee-b964f7139981

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2015-01-01..2015-04-01 (12 features)...

[I 2026-07-05 17:23:03,475] Trial 0 finished with value: 36.48561341614164 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 36.48561341614164.
[I 2026-07-05 17:23:05,896] Trial 1 finished with value: 35.78563844450228 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 35.78563844450228.
[I 2026-07-05 17:23:06,851] Trial 2 finished with value: 36.73601051650681 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 35.78563844450228.
[I 2026-07-05 17:23:08,485] Trial 3 finished with value: 35.79705363962004 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 35.78563844450228.
[I 2026-07-05 17:23:09,395] Trial 4 finished with value: 35.86833983349218 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 35.78563844450228.
[I 2026-07-05 17:23:11,934] Trial 5 finished with value: 35.671139925357025 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 35.671139925357025.
[I 2026-07-05 17:23:12,399] Trial 6 finished with value: 36.446215326126406 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 35.671139925357025.
[I 2026-07-05 17:23:16,832] Trial 7 finished with value: 35.64819016422209 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 35.64819016422209.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:25:34,773] A new study created in memory with name: no-name-ca5bfbfe-8da9-4eb2-8770-1191f6470a24

Retune 2015-07..2015-09: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2015-04-01..2015-07-01 (21 features)...

[I 2026-07-05 17:25:36,261] Trial 0 finished with value: 47.59755108129329 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 47.59755108129329.
[I 2026-07-05 17:25:39,959] Trial 1 finished with value: 46.81123421072468 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 46.81123421072468.
[I 2026-07-05 17:25:42,612] Trial 2 finished with value: 46.78929052109303 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 46.78929052109303.
[I 2026-07-05 17:25:47,338] Trial 3 finished with value: 40.171316322936256 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 40.171316322936256.
[I 2026-07-05 17:25:51,717] Trial 4 finished with value: 40.134589603295055 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 40.134589603295055.
[I 2026-07-05 17:25:54,649] Trial 5 finished with value: 47.74199363705431 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 40.134589603295055.
[I 2026-07-05 17:25:55,610] Trial 6 finished with value: 46.96926600431718 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 40.134589603295055.
[I 2026-07-05 17:26:02,318] Trial 7 finished with value: 42.077483861231315 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 40.134589603295055.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:26:02,333] A new study created in memory with name: no-name-09881f76-68c2-403f-8803-f82ce6afcb09

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2015-04-01..2015-07-01 (21 features)...

[I 2026-07-05 17:26:02,667] Trial 0 finished with value: 37.87309627747023 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.87309627747023.
[I 2026-07-05 17:26:03,465] Trial 1 finished with value: 37.832532318288656 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 37.832532318288656.
[I 2026-07-05 17:26:04,137] Trial 2 finished with value: 37.80976539302094 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 37.80976539302094.
[I 2026-07-05 17:26:05,853] Trial 3 finished with value: 38.20931157562751 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 37.80976539302094.
[I 2026-07-05 17:26:07,536] Trial 4 finished with value: 39.73369133910078 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 37.80976539302094.
[I 2026-07-05 17:26:09,689] Trial 5 finished with value: 38.0170085860677 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 37.80976539302094.
[I 2026-07-05 17:26:10,012] Trial 6 finished with value: 37.75283642299743 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 37.75283642299743.
[I 2026-07-05 17:26:12,048] Trial 7 finished with value: 37.77888141736303 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 37.75283642299743.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:26:12,062] A new study created in memory with name: no-name-a1bcc4e3-4818-4444-959e-a5b34a1a72a9

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2015-04-01..2015-07-01 (8 features)...

[I 2026-07-05 17:26:13,817] Trial 0 finished with value: 51.84199231346441 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 51.84199231346441.
[I 2026-07-05 17:26:16,707] Trial 1 finished with value: 51.28092000928237 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 51.28092000928237.
[I 2026-07-05 17:26:20,538] Trial 2 finished with value: 50.58844422989599 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 50.58844422989599.
[I 2026-07-05 17:26:23,638] Trial 3 finished with value: 47.617204997992644 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 47.617204997992644.
[I 2026-07-05 17:26:24,773] Trial 4 finished with value: 50.46635911611936 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 47.617204997992644.
[I 2026-07-05 17:26:27,270] Trial 5 finished with value: 50.94868103171634 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 47.617204997992644.
[I 2026-07-05 17:26:28,112] Trial 6 finished with value: 51.7223440933903 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 47.617204997992644.
[I 2026-07-05 17:26:33,282] Trial 7 finished with value: 48.79055942744695 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 47.617204997992644.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:26:33,296] A new study created in memory with name: no-name-30726954-f4c9-41f3-9058-84dbe96cd53c

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2015-04-01..2015-07-01 (8 features)...

[I 2026-07-05 17:26:33,596] Trial 0 finished with value: 38.159531833619056 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 38.159531833619056.
[I 2026-07-05 17:26:34,703] Trial 1 finished with value: 38.65214293247633 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 38.159531833619056.
[I 2026-07-05 17:26:38,088] Trial 2 finished with value: 40.49940673078579 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 38.159531833619056.
[I 2026-07-05 17:26:38,998] Trial 3 finished with value: 38.34503132351538 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 38.159531833619056.
[I 2026-07-05 17:26:39,441] Trial 4 finished with value: 38.00565485334572 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 38.00565485334572.
[I 2026-07-05 17:26:40,707] Trial 5 finished with value: 38.50822700828157 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 38.00565485334572.
[I 2026-07-05 17:26:41,553] Trial 6 finished with value: 40.28816285069491 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 38.00565485334572.
[I 2026-07-05 17:26:43,176] Trial 7 finished with value: 38.68354290416709 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 38.00565485334572.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:26:43,190] A new study created in memory with name: no-name-eb8bc5ab-6b43-43f1-b522-1b5c75a4019c

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2015-04-01..2015-07-01 (12 features)...

[I 2026-07-05 17:26:45,036] Trial 0 finished with value: 55.522903573811284 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 55.522903573811284.
[I 2026-07-05 17:26:48,260] Trial 1 finished with value: 53.9816523672957 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 53.9816523672957.
[I 2026-07-05 17:26:52,315] Trial 2 finished with value: 53.15027907080162 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 53.15027907080162.
[I 2026-07-05 17:26:57,665] Trial 3 finished with value: 46.90050129340295 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 46.90050129340295.
[I 2026-07-05 17:26:59,983] Trial 4 finished with value: 52.186533005982966 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 46.90050129340295.
[I 2026-07-05 17:27:02,635] Trial 5 finished with value: 54.46558588078656 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 46.90050129340295.
[I 2026-07-05 17:27:03,524] Trial 6 finished with value: 52.976963491462925 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 46.90050129340295.
[I 2026-07-05 17:27:12,228] Trial 7 finished with value: 48.34092313656417 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 46.90050129340295.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:27:12,242] A new study created in memory with name: no-name-4671430a-85c5-4959-a44e-3a793c485ef8

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2015-04-01..2015-07-01 (12 features)...

[I 2026-07-05 17:27:12,622] Trial 0 finished with value: 37.99247377756123 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 37.99247377756123.
[I 2026-07-05 17:27:13,466] Trial 1 finished with value: 37.641463914620346 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:14,107] Trial 2 finished with value: 37.850992064936825 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:15,142] Trial 3 finished with value: 37.643675336337175 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:15,657] Trial 4 finished with value: 37.85861651984319 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:16,652] Trial 5 finished with value: 37.72505628822277 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:17,024] Trial 6 finished with value: 37.859010513898426 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 37.641463914620346.
[I 2026-07-05 17:27:18,259] Trial 7 finished with value: 37.56480123682339 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 37.56480123682339.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:29:41,506] A new study created in memory with name: no-name-f4fef34d-ab22-4823-9a93-5a8c237a73ab

Retune 2015-10..2015-12: 92 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2015-07-01..2015-10-01 (21 features)...

[I 2026-07-05 17:29:43,540] Trial 0 finished with value: 64.42918892752613 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 64.42918892752613.
[I 2026-07-05 17:29:47,009] Trial 1 finished with value: 64.77320447113514 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 64.42918892752613.
[I 2026-07-05 17:29:50,023] Trial 2 finished with value: 64.45294129061669 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 64.42918892752613.
[I 2026-07-05 17:29:52,482] Trial 3 finished with value: 64.37921003396255 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 64.37921003396255.
[I 2026-07-05 17:29:53,483] Trial 4 finished with value: 64.9105225987027 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 64.37921003396255.
[I 2026-07-05 17:29:56,534] Trial 5 finished with value: 64.78998449240557 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 64.37921003396255.
[I 2026-07-05 17:29:57,504] Trial 6 finished with value: 65.03175658427458 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 64.37921003396255.
[I 2026-07-05 17:30:03,321] Trial 7 finished with value: 63.94944420207135 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 63.94944420207135.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:30:03,337] A new study created in memory with name: no-name-01453480-dc41-47b6-b8a3-a3d45e7b3cb3

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2015-07-01..2015-10-01 (21 features)...

[I 2026-07-05 17:30:03,652] Trial 0 finished with value: 63.67209572984798 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 63.67209572984798.
[I 2026-07-05 17:30:04,308] Trial 1 finished with value: 63.6776584236116 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 63.67209572984798.
[I 2026-07-05 17:30:04,800] Trial 2 finished with value: 63.675351131116024 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 63.67209572984798.
[I 2026-07-05 17:30:05,912] Trial 3 finished with value: 63.66155308517138 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 63.66155308517138.
[I 2026-07-05 17:30:06,414] Trial 4 finished with value: 63.65778280851509 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 63.65778280851509.
[I 2026-07-05 17:30:07,279] Trial 5 finished with value: 63.65488802403319 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 63.65488802403319.
[I 2026-07-05 17:30:07,586] Trial 6 finished with value: 63.63704590774047 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 63.63704590774047.
[I 2026-07-05 17:30:08,745] Trial 7 finished with value: 63.72860868488172 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 63.63704590774047.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:30:08,760] A new study created in memory with name: no-name-1e42510e-c68a-46e4-ad84-62bb6f3f3927

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2015-07-01..2015-10-01 (8 features)...

[I 2026-07-05 17:30:10,641] Trial 0 finished with value: 77.01220892714377 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 77.01220892714377.
[I 2026-07-05 17:30:13,648] Trial 1 finished with value: 72.4382696942481 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 72.4382696942481.
[I 2026-07-05 17:30:17,659] Trial 2 finished with value: 67.8429580128803 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 67.8429580128803.
[I 2026-07-05 17:30:20,205] Trial 3 finished with value: 69.68263171751008 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 67.8429580128803.
[I 2026-07-05 17:30:21,298] Trial 4 finished with value: 67.5906541294676 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 67.5906541294676.
[I 2026-07-05 17:30:23,908] Trial 5 finished with value: 74.18343831457797 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 67.5906541294676.
[I 2026-07-05 17:30:24,799] Trial 6 finished with value: 71.03361574638494 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 67.5906541294676.
[I 2026-07-05 17:30:31,399] Trial 7 finished with value: 68.78794678819891 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 67.5906541294676.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:30:31,414] A new study created in memory with name: no-name-d1f88dab-f981-4567-b2c8-e2315bca4389

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2015-07-01..2015-10-01 (8 features)...

[I 2026-07-05 17:30:31,675] Trial 0 finished with value: 63.66092570436811 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 63.66092570436811.
[I 2026-07-05 17:30:32,207] Trial 1 finished with value: 63.669302788530466 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 63.66092570436811.
[I 2026-07-05 17:30:32,663] Trial 2 finished with value: 63.669696948982704 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 63.66092570436811.
[I 2026-07-05 17:30:33,531] Trial 3 finished with value: 63.667349209042214 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 63.66092570436811.
[I 2026-07-05 17:30:33,986] Trial 4 finished with value: 63.547299537560335 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 63.547299537560335.
[I 2026-07-05 17:30:34,770] Trial 5 finished with value: 63.63750376835551 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 63.547299537560335.
[I 2026-07-05 17:30:35,060] Trial 6 finished with value: 63.59086907926345 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 63.547299537560335.
[I 2026-07-05 17:30:35,901] Trial 7 finished with value: 63.59920255711709 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 63.547299537560335.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:30:35,916] A new study created in memory with name: no-name-3d541cf4-8415-4d3c-b083-965b8f276512

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2015-07-01..2015-10-01 (12 features)...

[I 2026-07-05 17:30:37,900] Trial 0 finished with value: 86.12127534861348 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 86.12127534861348.
[I 2026-07-05 17:30:41,236] Trial 1 finished with value: 77.60991519759347 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 77.60991519759347.
[I 2026-07-05 17:30:45,371] Trial 2 finished with value: 80.24881095177354 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 77.60991519759347.
[I 2026-07-05 17:30:48,845] Trial 3 finished with value: 71.76107128299161 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 71.76107128299161.
[I 2026-07-05 17:30:51,937] Trial 4 finished with value: 69.65665332137036 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 69.65665332137036.
[I 2026-07-05 17:30:54,669] Trial 5 finished with value: 82.18163093787297 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 69.65665332137036.
[I 2026-07-05 17:30:55,612] Trial 6 finished with value: 81.20515925000518 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 69.65665332137036.
[I 2026-07-05 17:31:02,851] Trial 7 finished with value: 71.44439254529611 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 69.65665332137036.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:31:02,867] A new study created in memory with name: no-name-5c2ff43d-5aa2-4b49-b388-9ee92dfdf3a7

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2015-07-01..2015-10-01 (12 features)...

[I 2026-07-05 17:31:03,171] Trial 0 finished with value: 63.67676667633495 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 63.67676667633495.
[I 2026-07-05 17:31:03,756] Trial 1 finished with value: 63.674893447798844 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 63.674893447798844.
[I 2026-07-05 17:31:04,225] Trial 2 finished with value: 63.68089377038997 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 63.674893447798844.
[I 2026-07-05 17:31:05,181] Trial 3 finished with value: 63.73306955311091 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 63.674893447798844.
[I 2026-07-05 17:31:05,647] Trial 4 finished with value: 63.69736254280268 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 63.674893447798844.
[I 2026-07-05 17:31:06,440] Trial 5 finished with value: 63.68429213301897 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 63.674893447798844.
[I 2026-07-05 17:31:06,731] Trial 6 finished with value: 63.65260402591848 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 63.65260402591848.
[I 2026-07-05 17:31:07,602] Trial 7 finished with value: 63.67940809730634 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 63.65260402591848.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:33:17,794] A new study created in memory with name: no-name-f49b5814-7d31-40a3-951d-ab00ef1d22a9

Retune 2016-01..2016-03: 91 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2015-10-01..2016-01-01 (21 features)...

[I 2026-07-05 17:33:19,948] Trial 0 finished with value: 41.550147599281374 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:23,818] Trial 1 finished with value: 42.50223986131396 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:28,527] Trial 2 finished with value: 41.60131204561072 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:32,603] Trial 3 finished with value: 42.810091841394794 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:35,072] Trial 4 finished with value: 42.31365033397941 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:38,237] Trial 5 finished with value: 43.2724383882581 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:39,308] Trial 6 finished with value: 41.72061009279606 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 41.550147599281374.
[I 2026-07-05 17:33:52,209] Trial 7 finished with value: 40.77281978671787 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 40.77281978671787.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:33:52,225] A new study created in memory with name: no-name-24a642cd-d153-4fbb-b70d-9bc641d68d79

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2015-10-01..2016-01-01 (21 features)...

[I 2026-07-05 17:33:52,833] Trial 0 finished with value: 44.590647742225386 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:53,517] Trial 1 finished with value: 45.345614513727874 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:54,194] Trial 2 finished with value: 45.036443358562956 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:55,412] Trial 3 finished with value: 45.29452622274915 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:55,965] Trial 4 finished with value: 45.31714561336018 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:56,892] Trial 5 finished with value: 45.33814684989542 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:57,264] Trial 6 finished with value: 45.257236228002114 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 0 with value: 44.590647742225386.
[I 2026-07-05 17:33:58,471] Trial 7 finished with value: 45.226083489267864 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 0 with value: 44.590647742225386.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:33:58,487] A new study created in memory with name: no-name-2861391f-97fc-4bb7-b4e4-44e250c56272

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2015-10-01..2016-01-01 (8 features)...

[I 2026-07-05 17:34:00,477] Trial 0 finished with value: 47.645679789084255 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 47.645679789084255.
[I 2026-07-05 17:34:02,907] Trial 1 finished with value: 48.54400623008251 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 47.645679789084255.
[I 2026-07-05 17:34:06,891] Trial 2 finished with value: 49.606206792788115 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 47.645679789084255.
[I 2026-07-05 17:34:08,674] Trial 3 finished with value: 50.918521495086225 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 47.645679789084255.
[I 2026-07-05 17:34:09,625] Trial 4 finished with value: 47.05983025202823 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 4 with value: 47.05983025202823.
[I 2026-07-05 17:34:12,277] Trial 5 finished with value: 47.99804876927952 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 4 with value: 47.05983025202823.
[I 2026-07-05 17:34:13,224] Trial 6 finished with value: 48.47097742475974 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 4 with value: 47.05983025202823.
[I 2026-07-05 17:34:16,839] Trial 7 finished with value: 48.50528663635039 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 4 with value: 47.05983025202823.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:34:16,855] A new study created in memory with name: no-name-f69b9d98-19ae-4441-9bd1-430d1146af77

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2015-10-01..2016-01-01 (8 features)...

[I 2026-07-05 17:34:17,233] Trial 0 finished with value: 45.21071856685142 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:17,870] Trial 1 finished with value: 45.28860906828112 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:18,397] Trial 2 finished with value: 45.3151230463578 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:19,314] Trial 3 finished with value: 45.27158825361904 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:19,802] Trial 4 finished with value: 45.42128736460428 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:20,673] Trial 5 finished with value: 45.31194598070315 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 0 with value: 45.21071856685142.
[I 2026-07-05 17:34:20,987] Trial 6 finished with value: 45.1997064328178 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 6 with value: 45.1997064328178.
[I 2026-07-05 17:34:22,152] Trial 7 finished with value: 45.236333148295245 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 6 with value: 45.1997064328178.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:34:22,168] A new study created in memory with name: no-name-4836535e-4101-436e-8fcc-b157802a72d5

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2015-10-01..2016-01-01 (12 features)...

[I 2026-07-05 17:34:24,246] Trial 0 finished with value: 46.77874668850284 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 46.77874668850284.
[I 2026-07-05 17:34:27,709] Trial 1 finished with value: 45.651272628333075 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 45.651272628333075.
[I 2026-07-05 17:34:32,048] Trial 2 finished with value: 46.01687463548537 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 45.651272628333075.
[I 2026-07-05 17:34:38,914] Trial 3 finished with value: 44.45336916023673 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 44.45336916023673.
[I 2026-07-05 17:34:43,129] Trial 4 finished with value: 45.070055494010475 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 44.45336916023673.
[I 2026-07-05 17:34:45,935] Trial 5 finished with value: 45.97216417019043 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 44.45336916023673.
[I 2026-07-05 17:34:46,934] Trial 6 finished with value: 46.41118381099802 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 44.45336916023673.
[I 2026-07-05 17:34:54,481] Trial 7 finished with value: 45.2667978432853 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 3 with value: 44.45336916023673.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:34:54,497] A new study created in memory with name: no-name-4e758dac-1381-4dac-8640-885197a59e27

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2015-10-01..2016-01-01 (12 features)...

[I 2026-07-05 17:34:55,074] Trial 0 finished with value: 44.89840848656286 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.89840848656286.
[I 2026-07-05 17:34:56,349] Trial 1 finished with value: 44.870579614886246 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 44.870579614886246.
[I 2026-07-05 17:34:57,049] Trial 2 finished with value: 45.13664593926989 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 44.870579614886246.
[I 2026-07-05 17:34:58,098] Trial 3 finished with value: 45.24775541325604 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 44.870579614886246.
[I 2026-07-05 17:34:58,702] Trial 4 finished with value: 45.02578213455524 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 44.870579614886246.
[I 2026-07-05 17:35:00,391] Trial 5 finished with value: 44.79851503271263 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 44.79851503271263.
[I 2026-07-05 17:35:00,820] Trial 6 finished with value: 45.006497808445616 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 44.79851503271263.
[I 2026-07-05 17:35:02,700] Trial 7 finished with value: 44.60836140908141 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 44.60836140908141.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:37:58,524] A new study created in memory with name: no-name-055cb478-3c11-4351-a60c-d06c9f8e93f3

Retune 2016-04..2016-06: 91 validation origin(s), retrain every 7 day(s).
  Tuning price_full_engineered__direct__conservative__exp_hl180 on 2016-01-01..2016-04-01 (21 features)...

[I 2026-07-05 17:38:00,446] Trial 0 finished with value: 40.79886227354655 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 40.79886227354655.
[I 2026-07-05 17:38:03,212] Trial 1 finished with value: 39.09202755849371 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:07,508] Trial 2 finished with value: 39.57638611483758 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:09,800] Trial 3 finished with value: 39.428908191204364 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:10,660] Trial 4 finished with value: 45.34131677107043 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:13,182] Trial 5 finished with value: 41.63339985382327 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:14,136] Trial 6 finished with value: 39.49092306270435 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 1 with value: 39.09202755849371.
[I 2026-07-05 17:38:19,709] Trial 7 finished with value: 39.86775435276448 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 1 with value: 39.09202755849371.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:38:19,726] A new study created in memory with name: no-name-53c6dcae-a256-4733-be67-a78cd65c1dc7

  Tuning price_full_engineered__residual_baseline__conservative__exp_hl180 on 2016-01-01..2016-04-01 (21 features)...

[I 2026-07-05 17:38:22,124] Trial 0 finished with value: 42.4440377319189 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 42.4440377319189.
[I 2026-07-05 17:38:26,357] Trial 1 finished with value: 41.4973485944686 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 41.4973485944686.
[I 2026-07-05 17:38:30,130] Trial 2 finished with value: 43.01107624365396 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 41.4973485944686.
[I 2026-07-05 17:38:34,229] Trial 3 finished with value: 40.87409158054401 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 40.87409158054401.
[I 2026-07-05 17:38:35,579] Trial 4 finished with value: 41.8314315670523 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 40.87409158054401.
[I 2026-07-05 17:38:38,904] Trial 5 finished with value: 41.33109699723151 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 3 with value: 40.87409158054401.
[I 2026-07-05 17:38:39,784] Trial 6 finished with value: 43.77432372602325 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 3 with value: 40.87409158054401.
[I 2026-07-05 17:38:46,197] Trial 7 finished with value: 40.31629952925858 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 40.31629952925858.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:38:46,214] A new study created in memory with name: no-name-752553c0-4798-4849-9668-56dc2cb40b8e

  Tuning price_baseline_calendar__direct__conservative__exp_hl180 on 2016-01-01..2016-04-01 (8 features)...

[I 2026-07-05 17:38:48,460] Trial 0 finished with value: 41.33943542172597 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 41.33943542172597.
[I 2026-07-05 17:38:51,262] Trial 1 finished with value: 41.52454613645004 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 0 with value: 41.33943542172597.
[I 2026-07-05 17:38:55,729] Trial 2 finished with value: 40.57626658425143 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 40.57626658425143.
[I 2026-07-05 17:39:00,745] Trial 3 finished with value: 41.748604150209175 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 40.57626658425143.
[I 2026-07-05 17:39:01,993] Trial 4 finished with value: 40.81558052092144 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 40.57626658425143.
[I 2026-07-05 17:39:03,778] Trial 5 finished with value: 41.20853875359163 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 40.57626658425143.
[I 2026-07-05 17:39:04,862] Trial 6 finished with value: 40.99560334439877 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 40.57626658425143.
[I 2026-07-05 17:39:10,915] Trial 7 finished with value: 40.15401557003141 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 40.15401557003141.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:39:10,933] A new study created in memory with name: no-name-3bb8bf61-de58-4828-ab5f-d2172bb9e446

  Tuning price_baseline_calendar__residual_baseline__conservative__exp_hl180 on 2016-01-01..2016-04-01 (8 features)...

[I 2026-07-05 17:39:11,369] Trial 0 finished with value: 43.1779276832104 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 43.1779276832104.
[I 2026-07-05 17:39:14,691] Trial 1 finished with value: 41.8718168756348 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 41.8718168756348.
[I 2026-07-05 17:39:17,365] Trial 2 finished with value: 41.57805757147594 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 2 with value: 41.57805757147594.
[I 2026-07-05 17:39:18,948] Trial 3 finished with value: 41.75495041174494 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 2 with value: 41.57805757147594.
[I 2026-07-05 17:39:20,273] Trial 4 finished with value: 43.52506885624126 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 2 with value: 41.57805757147594.
[I 2026-07-05 17:39:23,101] Trial 5 finished with value: 42.031395256163314 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 2 with value: 41.57805757147594.
[I 2026-07-05 17:39:24,122] Trial 6 finished with value: 41.775056612882516 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 2 with value: 41.57805757147594.
[I 2026-07-05 17:39:27,150] Trial 7 finished with value: 41.672574971905306 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 2 with value: 41.57805757147594.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:39:27,169] A new study created in memory with name: no-name-c4a8a0a1-2c71-405d-96a7-83acd461e93f

  Tuning price_lags_calendar__direct__conservative__exp_hl180 on 2016-01-01..2016-04-01 (12 features)...

[I 2026-07-05 17:39:29,571] Trial 0 finished with value: 42.24865422320851 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 42.24865422320851.
[I 2026-07-05 17:39:33,279] Trial 1 finished with value: 39.52758844081509 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 39.52758844081509.
[I 2026-07-05 17:39:37,958] Trial 2 finished with value: 41.606657405410026 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 39.52758844081509.
[I 2026-07-05 17:39:40,733] Trial 3 finished with value: 39.80297683986263 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 1 with value: 39.52758844081509.
[I 2026-07-05 17:39:42,699] Trial 4 finished with value: 42.21342727242573 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 1 with value: 39.52758844081509.
[I 2026-07-05 17:39:45,726] Trial 5 finished with value: 39.49287641216323 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 4, 'learning_rate': 0.019663906569758867, 'l2_leaf_reg': 88.96916672592673, 'random_strength': 13.476034484393836, 'border_count': 32, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.9693523097955246, 'rsm': 0.7728284587275367}. Best is trial 5 with value: 39.49287641216323.
[I 2026-07-05 17:39:46,832] Trial 6 finished with value: 39.52960944577159 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 300, 'depth': 3, 'learning_rate': 0.037560889633913144, 'l2_leaf_reg': 25.644046794293644, 'random_strength': 11.15427244096465, 'border_count': 32, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8038815381119562, 'rsm': 0.6564274505389015}. Best is trial 5 with value: 39.49287641216323.
[I 2026-07-05 17:39:54,103] Trial 7 finished with value: 38.93045867724829 and parameters: {'bootstrap_type': 'Bayesian', 'iterations': 900, 'depth': 6, 'learning_rate': 0.014739730807520416, 'l2_leaf_reg': 144.9592822362263, 'random_strength': 11.708160354481713, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.181066446651219, 'rsm': 0.9012557041397201}. Best is trial 7 with value: 38.93045867724829.
/opt/homebrew/lib/python3.10/site-packages/optuna/_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-07-05 17:39:54,120] A new study created in memory with name: no-name-8df7cfb8-8f50-4d54-924b-fad11f4702fe

  Tuning price_lags_calendar__residual_baseline__conservative__exp_hl180 on 2016-01-01..2016-04-01 (12 features)...

[I 2026-07-05 17:39:56,426] Trial 0 finished with value: 44.72239529558799 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 700, 'depth': 3, 'learning_rate': 0.013831748681407519, 'l2_leaf_reg': 11.900590783184242, 'random_strength': 17.591170623948834, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 1, 'subsample': 0.7045474901621301, 'rsm': 0.6641915784487018}. Best is trial 0 with value: 44.72239529558799.
[I 2026-07-05 17:40:00,103] Trial 1 finished with value: 44.029176289925665 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 500, 'depth': 5, 'learning_rate': 0.013365201439497277, 'l2_leaf_reg': 23.99324290681271, 'random_strength': 8.594513179286452, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.8322634555704315, 'rsm': 0.6596834432905521}. Best is trial 1 with value: 44.029176289925665.
[I 2026-07-05 17:40:04,926] Trial 2 finished with value: 44.955963974712255 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 4, 'learning_rate': 0.01225199210177624, 'l2_leaf_reg': 77.66184280392886, 'random_strength': 9.922744887312824, 'border_count': 64, 'boosting_type': 'Plain', 'leaf_estimation_iterations': 3, 'subsample': 0.7435133228268233, 'rsm': 0.7820238074122338}. Best is trial 1 with value: 44.029176289925665.
[I 2026-07-05 17:40:12,137] Trial 3 finished with value: 43.672671285863004 and parameters: {'bootstrap_type': 'MVS', 'iterations': 800, 'depth': 6, 'learning_rate': 0.06428499585801385, 'l2_leaf_reg': 59.96333882412659, 'random_strength': 18.593736230416102, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 2, 'subsample': 0.8986212527455788, 'rsm': 0.7248636643427562}. Best is trial 3 with value: 43.672671285863004.
[I 2026-07-05 17:40:15,313] Trial 4 finished with value: 44.13322864323258 and parameters: {'bootstrap_type': 'Bernoulli', 'iterations': 800, 'depth': 3, 'learning_rate': 0.07784804502594384, 'l2_leaf_reg': 101.09125982108304, 'random_strength': 5.576882267615103, 'border_count': 64, 'boosting_type': 'Ordered', 'leaf_estimation_iterations': 1, 'subsample': 0.7575397185632817, 'rsm': 0.6405541708337954}. Best is trial 3 with value: 43.672671285863004.

### Price-Only Policy Diagnostics

For each policy, the selected path is the candidate chosen by inner tuning for each quarterly block. This means a policy can select different feature sets or target modes as it rolls forward; the policy score reflects that whole adaptive path.

In [ ]:
def selected_policy_predictions(results, *, family):
    frames = []
    for policy_label, result in results.items():
        selected = result.catboost_predictions[result.catboost_predictions["selected_by_tuning"]].copy()
        selected["candidate_model_label"] = selected["model_label"]
        selected["model_label"] = f"{family}_selected__{policy_label}"
        frames.append(selected)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def selected_policy_delta_table(results):
    frames = []
    for result in results.values():
        selected = result.per_origin_deltas[result.per_origin_deltas["selected_by_tuning"]].copy()
        frames.append(selected)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def selected_config_table(results):
    return concat_result_frames(results, "selected_validation_configs").sort_values(
        ["policy_label", "retune_at_utc", "candidate_label"]
    ).reset_index(drop=True)


def policy_score_table(results, *, family, baseline_predictions, policy_grid, backtest_months):
    selected = selected_policy_predictions(results, family=family)
    combined = pd.concat([baseline_predictions, selected], ignore_index=True)
    scores = model_score_table(combined)
    policy_scores = scores[
        scores["area"].eq("ALL")
        & scores["model_label"].str.startswith(f"{family}_selected__")
    ].copy()
    policy_scores["policy_label"] = policy_scores["model_label"].str.removeprefix(f"{family}_selected__")
    policy_scores["family"] = family
    policy_scores["backtest_start_month"] = backtest_months[0]
    policy_scores["backtest_end_month"] = backtest_months[-1]
    policy_scores["backtest_month_count"] = len(backtest_months)

    best_baseline = (
        scores[scores["area"].eq("ALL") & ~scores["model_label"].str.startswith(f"{family}_selected__")]
        .sort_values(["mae", "model_label"])
        .iloc[0]
    )
    policy_scores["best_baseline_label"] = best_baseline["model_label"]
    policy_scores["best_baseline_mae"] = float(best_baseline["mae"])
    policy_scores["mae_minus_best_baseline"] = policy_scores["mae"] - policy_scores["best_baseline_mae"]

    metadata = pd.DataFrame([policy_metadata(policy, family=family) for policy in policy_grid])
    return (
        policy_scores.merge(metadata, on=["family", "policy_label"], how="left")
        .sort_values(["mae", "policy_label"])
        .reset_index(drop=True)
    )


def policy_month_score_table(results, *, family, baseline_predictions):
    selected = selected_policy_predictions(results, family=family)
    combined = pd.concat([baseline_predictions, selected], ignore_index=True)
    scores = outer_month_score_table(combined)
    selected_scores = scores[
        scores["model_label"].str.startswith(f"{family}_selected__")
    ].copy()
    selected_scores["policy_label"] = selected_scores["model_label"].str.removeprefix(f"{family}_selected__")
    return selected_scores.sort_values(["policy_label", "outer_month"]).reset_index(drop=True)


price_policy_scores = policy_score_table(
    price_results,
    family="price",
    baseline_predictions=price_baseline_predictions,
    policy_grid=PRICE_POLICY_GRID,
    backtest_months=PRICE_BACKTEST_MONTHS,
)
price_policy_scores

In [ ]:
price_selected_configs = selected_config_table(price_results)
price_selected_configs[[
    "policy_label",
    "validation_block",
    "candidate_label",
    "feature_set",
    "target_mode",
    "recency_label",
    "tuning_mae",
    "retrain_every_days",
    "training_origin_days",
]].sort_values(["policy_label", "validation_block"])

In [ ]:
selected_price_deltas = selected_policy_delta_table(price_results)
selected_price_delta_summary = selected_price_deltas.groupby(["policy_label", "validation_block"]).agg(
    origins=("forecast_origin_utc", "nunique"),
    mean_delta=("catboost_minus_best_baseline_mae", "mean"),
    median_delta=("catboost_minus_best_baseline_mae", "median"),
    win_rate=("catboost_minus_best_baseline_mae", lambda s: (s < 0).mean()),
    mean_validation_minus_tuning=("validation_minus_tuning_mae", "mean"),
).reset_index()
selected_price_delta_summary.sort_values(["policy_label", "validation_block"])

In [ ]:
fig, ax = plt.subplots(figsize=(12, 5))
sns.boxplot(
    data=selected_price_deltas,
    x="policy_label",
    y="catboost_minus_best_baseline_mae",
    hue="validation_block",
    ax=ax,
)
ax.axhline(0, color="black", linewidth=1)
ax.set_title("Price CatBoost policies: selected-path per-origin MAE delta vs best baseline")
ax.set_ylabel("CatBoost MAE - best baseline MAE")
ax.set_xlabel("Policy")
ax.tick_params(axis="x", rotation=25)
plt.tight_layout()
plt.show()

<p style="color:#b00020"><strong>Interpretation.</strong> The relevant comparison is whether an adaptation policy stays below the baseline across several future blocks, not whether one candidate wins one convenient split. Watch for policies that win only in one quarter, policies where outer MAE is much worse than the inner tuning MAE, and policies that oscillate between direct and residual formulations.</p>

## 5. Weather-Enhanced Policy Grid

Weather features enter after the price-only policy story is visible. The weather grid uses the same policies and includes `price_full_engineered` as a no-weather anchor, so a weather policy can reveal when weather features are genuinely worth selecting and when the price-only signal is enough.

In [ ]:
weather_results = run_policy_grid(
    family="weather",
    feature_sets=WEATHER_FEATURE_SETS,
    output_dir=WEATHER_RESULT_DIR,
    experiment_frame=weather_frame,
    baseline_predictions=weather_baseline_predictions,
    backtest_months=WEATHER_BACKTEST_MONTHS,
    policy_grid=WEATHER_POLICY_GRID,
)

In [ ]:
weather_policy_scores = policy_score_table(
    weather_results,
    family="weather",
    baseline_predictions=weather_baseline_predictions,
    policy_grid=WEATHER_POLICY_GRID,
    backtest_months=WEATHER_BACKTEST_MONTHS,
)
weather_policy_scores

In [ ]:
weather_selected_configs = selected_config_table(weather_results)
weather_selected_configs[[
    "policy_label",
    "validation_block",
    "candidate_label",
    "feature_set",
    "target_mode",
    "recency_label",
    "tuning_mae",
    "retrain_every_days",
    "training_origin_days",
]].sort_values(["policy_label", "validation_block"])

### Weather Policy Diagnostics

A weather policy earns its keep only if the selected path improves future-block accuracy and actually chooses weather-conditioned feature sets often enough to justify the added data dependency.

In [ ]:
weather_feature_adoption = (
    weather_selected_configs.assign(uses_weather=lambda df: df["feature_set"].ne("price_full_engineered"))
    .groupby("policy_label")
    .agg(
        validation_blocks=("validation_block", "nunique"),
        weather_selected_blocks=("uses_weather", "sum"),
        weather_selection_rate=("uses_weather", "mean"),
        selected_feature_sets=("feature_set", lambda values: ", ".join(sorted(set(values)))),
    )
    .reset_index()
)
weather_feature_adoption

In [ ]:
selected_weather_deltas = selected_policy_delta_table(weather_results)
selected_weather_delta_summary = selected_weather_deltas.groupby(["policy_label", "validation_block"]).agg(
    origins=("forecast_origin_utc", "nunique"),
    mean_delta=("catboost_minus_best_baseline_mae", "mean"),
    median_delta=("catboost_minus_best_baseline_mae", "median"),
    win_rate=("catboost_minus_best_baseline_mae", lambda s: (s < 0).mean()),
    mean_validation_minus_tuning=("validation_minus_tuning_mae", "mean"),
).reset_index()
selected_weather_delta_summary.sort_values(["policy_label", "validation_block"])

In [ ]:
combined_policy_scores = pd.concat(
    [
        price_policy_scores.assign(experiment_family="price-only"),
        weather_policy_scores.assign(experiment_family="weather-grid"),
    ],
    ignore_index=True,
)
combined_policy_scores[[
    "experiment_family",
    "policy_label",
    "backtest_start_month",
    "backtest_end_month",
    "backtest_month_count",
    "model_label",
    "mae",
    "rmse",
    "bias",
    "best_baseline_label",
    "best_baseline_mae",
    "mae_minus_best_baseline",
    "retune_every_months",
    "retrain_every_days",
    "training_origin_days",
    "policy_recency_label",
]].sort_values("mae")

In [ ]:
fig, ax = plt.subplots(figsize=(12, 5))
plot_frame = pd.concat([
    selected_price_deltas.assign(experiment_family="price-only"),
    selected_weather_deltas.assign(experiment_family="weather-grid"),
], ignore_index=True)
sns.boxplot(
    data=plot_frame,
    x="policy_label",
    y="catboost_minus_best_baseline_mae",
    hue="experiment_family",
    ax=ax,
)
ax.axhline(0, color="black", linewidth=1)
ax.set_title("Selected CatBoost policy paths vs best baseline")
ax.set_ylabel("CatBoost MAE - best baseline MAE")
ax.set_xlabel("Policy")
ax.tick_params(axis="x", rotation=25)
plt.tight_layout()
plt.show()

In [ ]:
selected_weather_keys = weather_selected_configs[["policy_label", "candidate_label"]].drop_duplicates()
weather_importance = concat_result_frames(weather_results, "feature_importance")
selected_weather_importance = weather_importance.merge(
    selected_weather_keys,
    on=["policy_label", "candidate_label"],
    how="inner",
)
top_importance = (
    selected_weather_importance.groupby("feature", as_index=False)["importance"]
    .mean()
    .sort_values("importance", ascending=False)
    .head(25)
)
top_importance

In [ ]:
fig, ax = plt.subplots(figsize=(9, 7))
sns.barplot(data=top_importance, y="feature", x="importance", ax=ax, color="#54a24b")
ax.set_title("Top mean feature importances for selected weather-policy candidates")
ax.set_xlabel("Mean CatBoost importance")
ax.set_ylabel("")
plt.tight_layout()
plt.show()

<p style="color:#b00020"><strong>Interpretation.</strong> Weather is useful only if it improves the selected policy path across future blocks. If the weather grid mostly selects `price_full_engineered`, the policy is telling us that the extra data dependency is not consistently worth it under the current feature construction.</p>

## 6. Policy Selection Summary

This final section records exploratory winners at the policy level. Price-only policies are selected in the long EDS-price arena, while weather policies are selected in the shorter weather-overlap arena. Treat the two winners as within-arena choices, not as a direct apples-to-apples promotion gate; the output is meant to narrow the next experiment and identify the adaptation regime that deserves an honest holdout or live shadow run.

In [ ]:
def best_policy_row(policy_scores, *, experiment_family):
    best = policy_scores.sort_values(["mae", "policy_label"]).iloc[0].to_dict()
    best["experiment_family"] = experiment_family
    best["selection_rule"] = "lowest_selected_policy_validation_mae"
    return best


final_policy_selections = pd.DataFrame([
    best_policy_row(price_policy_scores, experiment_family="price-only"),
    best_policy_row(weather_policy_scores, experiment_family="weather-grid"),
])[[
    "experiment_family",
    "policy_label",
    "backtest_start_month",
    "backtest_end_month",
    "backtest_month_count",
    "model_label",
    "mae",
    "rmse",
    "bias",
    "best_baseline_label",
    "best_baseline_mae",
    "mae_minus_best_baseline",
    "retune_every_months",
    "retrain_every_days",
    "training_origin_days",
    "policy_recency_label",
    "policy_sample_weight_half_life_days",
    "policy_sample_weight_floor",
    "selection_rule",
]]

RESULT_ROOT.mkdir(parents=True, exist_ok=True)
price_policy_scores.to_parquet(RESULT_ROOT / "price_policy_scores.parquet", index=False)
weather_policy_scores.to_parquet(RESULT_ROOT / "weather_policy_scores.parquet", index=False)
combined_policy_scores.to_parquet(RESULT_ROOT / "combined_policy_scores.parquet", index=False)
price_selected_configs.to_parquet(RESULT_ROOT / "price_selected_policy_configs.parquet", index=False)
weather_selected_configs.to_parquet(RESULT_ROOT / "weather_selected_policy_configs.parquet", index=False)
final_policy_selections.to_parquet(RESULT_ROOT / "final_policy_selections.parquet", index=False)
final_policy_selections

In [ ]:
def chosen_policy_month_comparison(results, *, family, policy_label, final_label, baseline_predictions):
    result = results[policy_label]
    chosen = result.catboost_predictions[result.catboost_predictions["selected_by_tuning"]].copy()
    chosen["model_label"] = final_label
    comparison = outer_month_score_table(pd.concat([baseline_predictions, chosen], ignore_index=True))
    best_baseline_by_month = (
        comparison[~comparison["model_label"].eq(final_label)]
        .sort_values(["outer_month", "mae", "model_label"])
        .groupby("outer_month", as_index=False)
        .head(1)
        [["outer_month", "model_label", "mae"]]
        .rename(columns={"model_label": "best_baseline_label", "mae": "best_baseline_mae"})
    )
    chosen_by_month = comparison[comparison["model_label"].eq(final_label)].merge(
        best_baseline_by_month,
        on="outer_month",
        how="left",
    )
    chosen_by_month["family"] = family
    chosen_by_month["policy_label"] = policy_label
    chosen_by_month["mae_minus_best_baseline"] = chosen_by_month["mae"] - chosen_by_month["best_baseline_mae"]
    return chosen_by_month

price_best_policy_label = final_policy_selections.loc[
    final_policy_selections["experiment_family"].eq("price-only"),
    "policy_label",
].iloc[0]
weather_best_policy_label = final_policy_selections.loc[
    final_policy_selections["experiment_family"].eq("weather-grid"),
    "policy_label",
].iloc[0]

final_policy_month_comparison = pd.concat(
    [
        chosen_policy_month_comparison(
            price_results,
            family="price-only",
            policy_label=price_best_policy_label,
            final_label="best_price_catboost_policy",
            baseline_predictions=price_baseline_predictions,
        ),
        chosen_policy_month_comparison(
            weather_results,
            family="weather-grid",
            policy_label=weather_best_policy_label,
            final_label="best_weather_catboost_policy",
            baseline_predictions=weather_baseline_predictions,
        ),
    ],
    ignore_index=True,
)
final_policy_month_comparison.to_parquet(
    RESULT_ROOT / "final_policy_month_comparison.parquet",
    index=False,
)
final_policy_month_comparison.sort_values(["family", "outer_month"])

<p style="color:#b00020"><strong>Final modeling read.</strong> The notebook now records a rolling adaptation-policy comparison rather than a static candidate comparison. A good policy should win or stay competitive across multiple future blocks, avoid a large gap between inner tuning MAE and outer replay MAE, and keep its added complexity explainable. Production promotion remains manual and source-controlled: update the fixed CatBoost config/registry, run a smoke publish, and commit the result; notebook winners do not auto-promote.</p>